import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Medals.lua','Export.lua','Theme.lua','Toast.lua','Comms.lua','Dashboard.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
const api=`
__vals={[101]="12",[201]="1,234",[301]="12 Gold 34 Silver 5 Copper",[302]="2 Days 3 Hr",[401]="--",[501]="7"}
__cats={[1]={"Combat",-1},[2]={"Deaths",1},[3]={"Quests",-1},[4]={"Character",-1},[5]={"Dungeons & Raids",-1}}
__stats={[2]={{101,"Total deaths"}},[3]={{201,"Quests completed"},{401,"Highest hit"}},[4]={{301,"Total gold acquired"},{302,"Total time played"}},[5]={{501,"Dungeons entered"}}}
function GetStatisticsCategoryList() return {1,2,3,4,5} end
function GetCategoryInfo(id) return __cats[id][1],__cats[id][2] end
function GetCategoryNumAchievements(id) return #(__stats[id] or {}),0,0 end
function GetAchievementInfo(id,index) local s=__stats[id][index] return s[1],s[2] end
function GetStatistic(id) return __vals[id],false end
function InCombatLockdown() return __combat==true end`;
const timers='__timers={}; C_Timer={After=function(d,f) table.insert(__timers,f) end}';
function setup(prelude=api,options={}){const h=createHarness(options);h.load(files.slice(0,1));h.run(prelude);h.load(files.slice(1));h.run('MAMChronicles:Boot()');return h;}
const key='Player-1234-ABCDEF';
const row=`MAMChroniclesDB.statistics["${key}"]`;

test('statistic value parser understands counts, money, durations and placeholders',()=>{const h=setup('');h.run('local P=MAMChronicles.AchievementStats; __a,__ak=P:ParseValue("1,234"); __b=P:ParseValue("--"); __c,__ck=P:ParseValue("12 Gold 34 Silver 5 Copper"); __d,__dk=P:ParseValue("2 Days 3 Hr"); __e=P:ParseValue("Never"); __f=P:ParseValue(nil)');assert.equal(h.get('__a'),1234);assert.equal(h.get('__ak'),'count');assert.equal(h.get('__b'),null);assert.equal(h.get('__c'),123405);assert.equal(h.get('__ck'),'money');assert.equal(h.get('__d'),183600);assert.equal(h.get('__dk'),'duration');assert.equal(h.get('__e'),null);assert.equal(h.get('__f'),null);});
test('scan degrades safely when the statistics APIs are absent',()=>{const h=setup('');h.run('__ok=MAMChronicles.AchievementStats:Scan()');assert.equal(h.get('__ok'),false);assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'unavailable');assert.equal(h.get('next(MAMChroniclesDB.statistics)'),null);});
test('scan stores a per-character baseline and latest snapshot with groups',()=>{const h=setup();h.run('__ok=MAMChronicles.AchievementStats:Scan()');assert.equal(h.get('__ok'),true);assert.equal(h.get(`${row}.baseline.values[101]`),12);assert.equal(h.get(`${row}.latest.values[201]`),1234);assert.equal(h.get('MAMChroniclesDB.statisticCatalog[101].group'),'Deaths and combat');assert.equal(h.get('MAMChroniclesDB.statisticCatalog[201].group'),'Quests');assert.equal(h.get('MAMChroniclesDB.statisticCatalog[302].group'),'Time played');assert.equal(h.get('MAMChroniclesDB.statisticCatalog[501].group'),'Dungeons and raids');assert.equal(h.get(`${row}.latest.values[401]`),null);assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'ok');});
test('gold statistics are excluded by default and stored only when enabled',()=>{const h=setup();h.run('MAMChronicles.AchievementStats:Scan()');assert.equal(h.get(`${row}.latest.values[301]`),null);assert.equal(h.get('MAMChroniclesDB.statisticCatalog[301]'),null);h.run('MAMChroniclesDB.settings.recordGoldStatistics=true; MAMChronicles.AchievementStats:Scan()');assert.equal(h.get(`${row}.latest.values[301]`),123405);assert.equal(h.get('MAMChroniclesDB.statisticCatalog[301].group'),'Gold and money');});
test('second scan keeps the baseline and reports changes since the month snapshot',()=>{const h=setup();h.run(`local P=MAMChronicles.AchievementStats; P:Scan(); __vals[101]="15"; __vals[201]="1,240"; P:Scan(); __top=P:GetTopChanges("${key}",5)`);assert.equal(h.get(`${row}.baseline.values[101]`),12);assert.equal(h.get(`${row}.latest.values[101]`),15);assert.equal(h.get('#__top'),2);assert.equal(h.get('__top[1].name'),'Quests completed');assert.equal(h.get('__top[1].delta'),6);assert.equal(h.get('__top[2].delta'),3);assert.equal(h.get('__top[2].group'),'Deaths and combat');});
test('a new calendar month gets its own starting snapshot and old months are pruned',()=>{const h=setup();h.run(`local P=MAMChronicles.AchievementStats; P:Scan(); for i=1,15 do ${row}.months["1999-"..string.format("%02d",i)]={takenAt=1,values={}} end; MAMChronicles.Now=function() return 1793400000 end; __vals[101]="20"; P:Scan()`);assert.notEqual(h.get(`${row}.months["2026-10"]`),null);const count=h.get(`(function() local n=0 for _ in pairs(${row}.months) do n=n+1 end return n end)()`);assert.equal(count<=6,true);});
test('disabling gold statistics purges stored gold values',()=>{const h=setup();h.run('MAMChroniclesDB.settings.recordGoldStatistics=true; MAMChronicles.AchievementStats:Scan(); MAMChronicles.SettingsPanel:ApplySetting("recordGoldStatistics",false)');assert.equal(h.get(`${row}.latest.values[301]`),null);assert.equal(h.get(`${row}.baseline.values[301]`),null);assert.equal(h.get('MAMChroniclesDB.statisticCatalog[301]'),null);assert.equal(h.get(`${row}.latest.values[101]`),12);});
test('scan is deferred during combat and retried later',()=>{const h=setup(`${api}; ${timers}`);h.run('__combat=true; __ok=MAMChronicles.AchievementStats:Scan()');assert.equal(h.get('__ok'),false);assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'pending');assert.equal(h.get('#__timers'),1);h.run('__combat=false; __timers[1]()');assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'ok');});
test('entering the world schedules one delayed scan per session',()=>{const h=setup(`${api}; ${timers}`);h.fire('PLAYER_ENTERING_WORLD');h.fire('PLAYER_ENTERING_WORLD');assert.equal(h.get('#__timers'),1);h.run('__timers[1]()');assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'ok');});
test('statistics settings have safe defaults and validated toggles',()=>{const h=setup('',{savedVariables:{schemaVersion:1,meta:{},settings:{recordStatistics:'yes',recordGoldStatistics:1},characters:{},sessions:{},events:{},eventIds:{},questCompletion:{},professionSnapshots:{},aggregates:{},diagnostics:{}}});assert.equal(h.get('MAMChroniclesDB.settings.recordStatistics'),true);assert.equal(h.get('MAMChroniclesDB.settings.recordGoldStatistics'),false);h.run('MAMChronicles.SettingsPanel:ApplySetting("recordStatistics",false); MAMChronicles.AchievementStats:Scan()');assert.equal(h.get('MAMChroniclesDB.settings.recordStatistics'),false);assert.equal(h.get('MAMChronicles.AchievementStats.status.state'),'disabled');});
test('erasing Chronicle history also clears statistics',()=>{const h=setup();h.run('MAMChronicles.AchievementStats:Scan(); MAMChronicles.Database:ClearHistory()');assert.equal(h.get('next(MAMChroniclesDB.statistics)'),null);assert.equal(h.get('next(MAMChroniclesDB.statisticCatalog)'),null);});
test('statistics text summarises groups and monthly changes and appears in the Statistics tab',()=>{const h=setup();h.run(`local P=MAMChronicles.AchievementStats; P:Scan(); __vals[101]="15"; P:Scan(); __text=P:BuildText("${key}"); MAMChronicles.UI:Show(); MAMChronicles.UI:SetActiveTab("Statistics")`);assert.match(h.get('__text'),/Lifetime statistics/);assert.match(h.get('__text'),/Deaths and combat/);assert.match(h.get('__text'),/Total deaths/);assert.match(h.get('__text'),/\+3/);assert.match(h.get('__text'),/since \d\d \w{3}/);assert.doesNotMatch(h.get('__text'),/gold/i);assert.match(h.get('MAMChronicles.UI.content.text'),/Lifetime statistics/);});
test('scan counts unreadable statistic formats and diagnostics report the status',()=>{const h=setup(api.replace('[501]="7"','[501]="7",[601]="12,000 yards"').replace('{501,"Dungeons entered"}','{501,"Dungeons entered"},{601,"Distance travelled"}'));h.run('MAMChronicles.AchievementStats:Scan(); __diag=MAMChronicles.Export:BuildDiagnosticReport()');assert.equal(h.get('MAMChronicles.AchievementStats.status.unparsed'),1);assert.match(h.get('__diag'),/Statistics: ok, 4 read, 1 unreadable/);});
test('diagnostics say statistics are unavailable when the APIs are missing',()=>{const h=setup('');h.run('MAMChronicles.AchievementStats:Scan(); __diag=MAMChronicles.Export:BuildDiagnosticReport()');assert.match(h.get('__diag'),/Statistics: unavailable/);});
test('statistics text shows headline lifetime values per group, not just counts',()=>{const h=setup();h.run(`local P=MAMChronicles.AchievementStats; P:Scan(); __text=P:BuildText("${key}")`);assert.match(h.get('__text'),/Total deaths 12/);assert.match(h.get('__text'),/Quests completed 1,234/);assert.match(h.get('__text'),/Total time played 2d 3h/);assert.doesNotMatch(h.get('__text'),/tracked/);});
test('diagnostics list sample unreadable values and uncategorised category names',()=>{const h=setup(api.replace('[501]="7"','[501]="7",[601]="12,000 yards",[701]="9"').replace('{501,"Dungeons entered"}','{501,"Dungeons entered"},{601,"Distance travelled"}').replace('[5]={"Dungeons & Raids",-1}}','[5]={"Dungeons & Raids",-1},[6]={"Mystery Realm",-1}}').replace('__stats={','__stats={[6]={{701,"Battles won"}},').replace('return {1,2,3,4,5}','return {1,2,3,4,5,6}'));h.run('MAMChronicles.AchievementStats:Scan(); __diag=MAMChronicles.Export:BuildDiagnosticReport()');assert.match(h.get('__diag'),/Unreadable sample: Distance travelled = 12,000 yards/);assert.match(h.get('__diag'),/Uncategorised: Mystery Realm \(1\)/);});
test('parser reads counts followed by a bracketed label',()=>{const h=setup('');h.run('local P=MAMChronicles.AchievementStats; __a,__ak=P:ParseValue("16025 (Humanoid)"); __b=P:ParseValue("9 ()"); __c=P:ParseValue("1,200 (Heavy Wool Bandage)"); __d=P:ParseValue("(Humanoid)")');assert.equal(h.get('__a'),16025);assert.equal(h.get('__ak'),'count');assert.equal(h.get('__b'),9);assert.equal(h.get('__c'),1200);assert.equal(h.get('__d'),null);});
test('live Retail root categories get their own groups instead of Other',()=>{const h=setup('');h.run('local P=MAMChronicles.AchievementStats; __w=P:Classify("World Events","Brewfest"); __p=P:Classify("Pet Battles","Battles won"); __l=P:Classify("Legacy","Old thing"); __c=P:Classify("Character","Highest Score"); __u=P:Classify("Mystery","x")');assert.equal(h.get('__w'),'World events');assert.equal(h.get('__p'),'Pet battles');assert.equal(h.get('__l'),'Legacy');assert.equal(h.get('__c'),'Character');assert.equal(h.get('__u'),'Other');});
test('parser returns the bracketed label alongside the count',()=>{const h=setup('');h.run('local P=MAMChronicles.AchievementStats; __n,__k,__l=P:ParseValue("16025 (Humanoid)"); __e,__ek,__el=P:ParseValue("9 ()")');assert.equal(h.get('__n'),16025);assert.equal(h.get('__l'),'Humanoid');assert.equal(h.get('__e'),9);assert.equal(h.get('__el'),null);});
test('labels are stored with the latest snapshot and shown in the statistics text',()=>{const h=setup(api.replace('[501]="7"','[501]="7",[701]="16,025 (Humanoid)"').replace('{501,"Dungeons entered"}','{501,"Dungeons entered"},{701,"Creature type killed the most"}'));h.run(`local P=MAMChronicles.AchievementStats; P:Scan(); __text=P:BuildText("${key}")`);assert.equal(h.get(`${row}.latest.labels[701]`),'Humanoid');assert.match(h.get('__text'),/Creature type killed the most 16,025 \(Humanoid\)/);});
