import test from 'node:test'; import assert from 'node:assert/strict'; import { createHarness, multi } from './harness.js';
const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua'];
function boot(globals={}){const h=createHarness({globals});h.load(files);h.run('MAMChronicles:Boot()');return h;}
test('collectors register independently and record sessions levels and quests',()=>{const h=boot({C_QuestLog:{GetTitleForQuestID:id=>id===77?'The Test Quest':null}});assert.ok(Number(h.get('#__mamCalls.registered'))>=15);h.fire('PLAYER_LOGIN');h.fire('PLAYER_LEVEL_UP',12);h.fire('QUEST_ACCEPTED',0,77);h.fire('QUEST_TURNED_IN',77);assert.equal(h.get('MAMChronicles.EventStore:Count("character.level_up")'),1);assert.equal(h.get('MAMChroniclesDB.questCompletion[77]'),1790704800);assert.equal(h.get('MAMChroniclesDB.events[4].payload.questName'),'The Test Quest');});
test('QUEST_ACCEPTED records the Retail quest ID supplied as the first argument',()=>{const h=boot({C_QuestLog:{GetTitleForQuestID:id=>id===77?'The Retail Quest':null}});h.fire('QUEST_ACCEPTED',77);assert.equal(h.get('MAMChronicles.EventStore:Count("quest.accepted")'),1);assert.equal(h.get('MAMChroniclesDB.events[1].payload.questID'),77);assert.equal(h.get('MAMChroniclesDB.events[1].payload.questName'),'The Retail Quest');});
test('death and resurrection are truthful and coordinates can be disabled',()=>{const h=boot({GetZoneText:()=> 'Test Zone',GetSubZoneText:()=> 'Cliff',C_Map:{GetBestMapForUnit:()=>99,GetPlayerMapPosition:()=>({GetXY:()=>multi(.2,.3)})},UnitCanAttack:()=>false});h.fire('PLAYER_DEAD');h.fire('PLAYER_ALIVE');assert.equal(h.get('MAMChroniclesDB.events[1].payload.zone'),'Test Zone');assert.equal(h.get('MAMChroniclesDB.events[1].payload.lastHostileTarget'),null);h.run('MAMChroniclesDB.settings.recordCoordinates=false; __loc=MAMChronicles.Collectors:CaptureLocation()');assert.equal(h.get('__loc.x'),null);});
test('zone signals deduplicate and instance transitions are captured',()=>{let inside=false;const h=boot({GetZoneText:()=> 'Valley',C_Map:{GetBestMapForUnit:()=>5},IsInInstance:()=>inside?multi(true,'party'):multi(false,'none'),GetInstanceInfo:()=>multi('Test Dungeon','party',1,'Normal',5,0,false,42)});h.fire('ZONE_CHANGED');h.fire('ZONE_CHANGED_NEW_AREA');inside=true;h.fire('PLAYER_ENTERING_WORLD');inside=false;h.fire('PLAYER_ENTERING_WORLD');assert.equal(h.get('MAMChronicles.EventStore:Count("world.zone_discovered")'),1);assert.equal(h.get('MAMChronicles.EventStore:Count("instance.entered")'),1);assert.equal(h.get('MAMChronicles.EventStore:Count("instance.exited")'),1);});
test('notable loot waits for item data and ignores uncommon items',()=>{let ready=false;const h=boot({LOOT_ITEM_SELF:'You receive loot: %s.',GetItemInfo:item=>ready?multi('Epic Sword','|cffa335ee|Hitem:123::::::::|h[Epic Sword]|h|r',4,100,0,'Weapon','Sword',1,'INVTYPE_WEAPON',0,0,4):multi(null),GetItemInfoInstant:()=>multi(123)});h.fire('CHAT_MSG_LOOT','You receive loot: |cffa335ee|Hitem:123::::::::|h[Epic Sword]|h|r.');assert.equal(h.get('MAMChronicles.EventStore:Count("loot.notable")'),0);ready=true;h.fire('GET_ITEM_INFO_RECEIVED',123,true);assert.equal(h.get('MAMChroniclesDB.events[1].payload.itemID'),123);assert.equal(h.get('MAMChroniclesDB.events[1].payload.quality'),4);});
test('profession snapshots only record changes and manual memories validate text',()=>{let rank=1;const h=boot({GetProfessions:()=>multi(1),GetProfessionInfo:()=>multi('Cooking',null,rank,75,null,null,185,0)});h.fire('SKILL_LINES_CHANGED');h.fire('SKILL_LINES_CHANGED');rank=2;h.fire('SKILL_LINES_CHANGED');assert.equal(h.get('MAMChronicles.EventStore:Count("profession.changed")'),2);assert.equal(h.get('MAMChroniclesDB.events[1].payload.professionID'),185);h.run('__a=MAMChronicles.Collectors:RecordManualMemory("  A fine day  "); __b=MAMChronicles.Collectors:RecordManualMemory("   ")');assert.equal(h.get('__a.type'),'memory.manual');assert.equal(h.get('__a.payload.text'),'A fine day');assert.equal(h.get('__b'),null);});
test('throwing optional APIs do not stop other collectors',()=>{const h=boot({GetZoneText:()=>{throw new Error('blocked')}});h.fire('ZONE_CHANGED');h.fire('PLAYER_LEVEL_UP',20);assert.equal(h.get('MAMChronicles.EventStore:Count("character.level_up")'),1);assert.equal(h.get('MAMChronicles.EventStore:Query({type="character.level_up"})[1].payload.level'),20);});
test('secondary profession slots with leading nils are captured',()=>{const h=boot({GetProfessions:()=>multi(null,null,null,null,5),GetProfessionInfo:()=>multi('Cooking',null,25,75,null,null,185,0)});h.fire('SKILL_LINES_CHANGED');assert.equal(h.get('MAMChronicles.EventStore:Count("profession.changed")'),1);assert.equal(h.get('MAMChroniclesDB.events[1].payload.professionName'),'Cooking');assert.equal(h.get('MAMChroniclesDB.events[1].payload.professionID'),185);});
test('PLAYER_ALIVE only records a return after an observed death',()=>{const h=boot();h.fire('PLAYER_ALIVE');assert.equal(h.get('MAMChronicles.EventStore:Count("character.resurrected")'),0);h.fire('PLAYER_DEAD');h.fire('PLAYER_ALIVE');assert.equal(h.get('MAMChronicles.EventStore:Count("character.resurrected")'),1);});
test('achievement fallback uses the documented name and points positions',()=>{const h=boot({GetAchievementInfo:()=>multi(55,'A Real Achievement',10)});h.fire('ACHIEVEMENT_EARNED',55);assert.equal(h.get('MAMChroniclesDB.events[1].payload.achievementName'),'A Real Achievement');assert.equal(h.get('MAMChroniclesDB.events[1].payload.points'),10);});
test('achievement event flags are never mistaken for names',()=>{const h=boot({GetAchievementInfo:()=>multi(55,'A Real Achievement',10)});h.fire('ACHIEVEMENT_EARNED',55,true);assert.equal(h.get('MAMChroniclesDB.events[1].payload.achievementName'),'A Real Achievement');});
test('loot collector ignores messages that are not the localized self format',()=>{const h=boot({LOOT_ITEM_SELF:'You receive loot: %s.',GetItemInfo:()=>multi('Epic','|Hitem:9|h[Epic]|h',4),GetItemInfoInstant:()=>multi(9)});h.fire('CHAT_MSG_LOOT','Someone receives loot: |Hitem:9|h[Epic]|h.');assert.equal(h.get('MAMChronicles.EventStore:Count("loot.notable")'),0);});
test('localized multiple self-loot records the proven quantity',()=>{const h=boot({LOOT_ITEM_SELF:'You receive loot: %s.',LOOT_ITEM_SELF_MULTIPLE:'You receive loot: %sx%d.',GetItemInfo:()=>multi('Epic Shard','|Hitem:9|h[Epic Shard]|h',4),GetItemInfoInstant:()=>multi(9)});h.fire('CHAT_MSG_LOOT','You receive loot: |Hitem:9|h[Epic Shard]|hx3.');assert.equal(h.get('MAMChronicles.EventStore:Count("loot.notable")'),1);assert.equal(h.get('MAMChroniclesDB.events[1].payload.quantity'),3);});
test('positional localized multiple self-loot formats are supported',()=>{const h=boot({LOOT_ITEM_SELF:'You receive loot: %s.',LOOT_ITEM_SELF_MULTIPLE:'You receive loot: %1$sx%2$d.',GetItemInfo:()=>multi('Epic Shard','|Hitem:9|h[Epic Shard]|h',4),GetItemInfoInstant:()=>multi(9)});h.fire('CHAT_MSG_LOOT','You receive loot: |Hitem:9|h[Epic Shard]|hx4.');assert.equal(h.get('MAMChronicles.EventStore:Count("loot.notable")'),1);assert.equal(h.get('MAMChroniclesDB.events[1].payload.quantity'),4);});
test('unsupported signals and unknown quest titles never invent facts',()=>{const h=boot();h.fire('NOT_A_WOW_EVENT','private');h.fire('QUEST_ACCEPTED',0,88);assert.equal(h.get('#MAMChroniclesDB.events'),1);assert.equal(h.get('MAMChroniclesDB.events[1].payload.questID'),88);assert.equal(h.get('MAMChroniclesDB.events[1].payload.questName'),null);});
test('self-loot below the configured quality threshold is ignored',()=>{const h=boot({LOOT_ITEM_SELF:'You receive loot: %s.',GetItemInfo:()=>multi('Uncommon','|Hitem:8|h[Uncommon]|h',3),GetItemInfoInstant:()=>multi(8)});h.fire('CHAT_MSG_LOOT','You receive loot: |Hitem:8|h[Uncommon]|h.');assert.equal(h.get('MAMChronicles.EventStore:Count("loot.notable")'),0);});
