import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Medals.lua','Counters.lua','Export.lua','Theme.lua','Toast.lua','Comms.lua','Dashboard.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
const api=`
__vals={[301]="30",[302]="80",[303]="12"}
__cats={[4]={"Social",-1}}
__stats={[4]={{301,"Total hugs"},{302,"Total waves"},{303,"Number of times hearthed"}}}
function GetStatisticsCategoryList() return {4} end
function GetCategoryInfo(id) return __cats[id][1],__cats[id][2] end
function GetCategoryNumAchievements(id) return #(__stats[id] or {}),0,0 end
function GetAchievementInfo(id,index) local s=__stats[id][index] return s[1],s[2] end
function GetStatistic(id) return __vals[id],false end
__hooks={}; __t=100; __actions={}; __mounted=false; __afk=false; __resting=false
function hooksecurefunc(a,b,c) if type(a)=="table" then __hooks[b]=c else __hooks[a]=b end end
function GetTime() return __t end
function GetActionInfo(slot) local a=__actions[slot] if a then return "item",a end end
__names={[1]="Bottle of Red Wine",[2]="Pale Ale",[3]="Hearty Stew",[4]="Scale Armor"}
C_Item={GetItemNameByID=function(id) return __names[id] end}
C_Container={GetContainerItemInfo=function(bag,slot) return {itemID=__bagItem} end,UseContainerItem=function() end}
function JumpOrAscendStart() end
function IsMounted() return __mounted end
function UnitIsAFK() return __afk end
function IsResting() return __resting end`;
function setup(extra=''){const h=createHarness();h.load(files.slice(0,1));h.run(api+'\n'+extra);h.load(files.slice(1));h.run('MAMChronicles:Boot(); MAMChronicles.AchievementStats:Scan()');return h;}
const counter=(name)=>`(MAMChroniclesDB.counters["Player-1234-ABCDEF"] or {}).${name}`;

test('item names are classified by whole-word keywords',()=>{const h=setup();h.run('local C=MAMChronicles.Counters; local function has(list,x) for _,v in ipairs(list) do if v==x then return true end end return false end; __wine=has(C:ClassifyItem("Bottle of Red Wine"),"wine"); __ale=has(C:ClassifyItem("Frothy Pale Ale"),"ale"); __scale=#C:ClassifyItem("Scale Armor"); __whale=#C:ClassifyItem("Whale Blubber"); __coffee=has(C:ClassifyItem("Mom\'s Coffee"),"coffee"); __tea=has(C:ClassifyItem("Jasmine Tea"),"coffee"); __food=has(C:ClassifyItem("Hearty Stew"),"food"); __band=has(C:ClassifyItem("Heavy Linen Bandage"),"bandage"); __pot=has(C:ClassifyItem("Greater Healing Potion"),"potion"); __steak=#C:ClassifyItem("Steakhouse Key")');assert.equal(h.get('__wine'),true);assert.equal(h.get('__ale'),true);assert.equal(h.get('__scale'),0);assert.equal(h.get('__whale'),0);assert.equal(h.get('__coffee'),true);assert.equal(h.get('__tea'),true);assert.equal(h.get('__food'),true);assert.equal(h.get('__band'),true);assert.equal(h.get('__pot'),true);assert.equal(h.get('__steak'),0);});
test('using a wine from the action bar counts once the cast succeeds',()=>{const h=setup();h.run('__actions[5]=1; __hooks.UseAction(5)');assert.equal(h.get(counter('wine')),null);h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',123);assert.equal(h.get(counter('wine')),1);h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',123);assert.equal(h.get(counter('wine')),1);});
test('a keybind pressed while the item is on cooldown does not count',()=>{const h=setup();h.run('__actions[5]=1; __hooks.UseAction(5); __t=110');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',123);assert.equal(h.get(counter('wine')),null);});
test('mashing the same item within a moment counts once',()=>{const h=setup();h.run('__actions[5]=2; __hooks.UseAction(5); __hooks.UseAction(5); __hooks.UseAction(5)');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',1);assert.equal(h.get(counter('ale')),1);});
test('using an item from the bags is counted too',()=>{const h=setup();h.run('__bagItem=3; __hooks.UseContainerItem(0,1)');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',1);assert.equal(h.get(counter('food')),1);});
test('casts by other units and unrelated items are ignored',()=>{const h=setup();h.run('__actions[5]=4; __hooks.UseAction(5)');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',1);assert.equal(h.get(`next(MAMChroniclesDB.counters)`),null);h.run('__actions[6]=1; __hooks.UseAction(6)');h.fire('UNIT_SPELLCAST_SUCCEEDED','target','guid',1);assert.equal(h.get(counter('wine')),null);});
test('jumps, mounting, going AFK, resting and screenshots are counted',()=>{const h=setup();h.run('__hooks.JumpOrAscendStart(); __hooks.JumpOrAscendStart()');assert.equal(h.get(counter('jumps')),2);h.run('__mounted=true');h.fire('PLAYER_MOUNT_DISPLAY_CHANGED');h.fire('PLAYER_MOUNT_DISPLAY_CHANGED');h.run('__mounted=false');h.fire('PLAYER_MOUNT_DISPLAY_CHANGED');h.run('__mounted=true');h.fire('PLAYER_MOUNT_DISPLAY_CHANGED');assert.equal(h.get(counter('mounts')),2);h.run('__afk=true');h.fire('PLAYER_FLAGS_CHANGED','player');h.fire('PLAYER_FLAGS_CHANGED','player');assert.equal(h.get(counter('afk')),1);h.run('__afk=false');h.fire('PLAYER_FLAGS_CHANGED','player');h.run('__afk=true');h.fire('PLAYER_FLAGS_CHANGED','player');assert.equal(h.get(counter('afk')),2);h.run('__resting=true');h.fire('PLAYER_UPDATE_RESTING');assert.equal(h.get(counter('rest')),1);h.fire('SCREENSHOT_SUCCEEDED');assert.equal(h.get(counter('shots')),1);});
test('counters only store numbers, never item names',()=>{const h=setup();h.run('__actions[5]=1; __hooks.UseAction(5)');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',1);h.run('__all=true; for k,v in pairs(MAMChroniclesDB.counters["Player-1234-ABCDEF"]) do if type(k)~="string" or type(v)~="number" then __all=false end end');assert.equal(h.get('__all'),true);});
test('drinking wine earns Wine O\'Clock live after the baseline',()=>{const h=setup();h.run('__seen={}; MAMChronicles.Medals:AddListener(function(def,info) table.insert(__seen,def and def.id) end); __actions[5]=1; __hooks.UseAction(5)');h.fire('UNIT_SPELLCAST_SUCCEEDED','player','guid',1);h.run('MAMChronicles.Medals:Evaluate("test")');assert.equal(h.get('__seen[1]'),'wine_1');});
test('social statistics earn the silly medals in the baseline',()=>{const h=setup();assert.notEqual(h.get('MAMChroniclesDB.medals["Player-1234-ABCDEF"].earned.hugs_1.at'),null);assert.notEqual(h.get('MAMChroniclesDB.medals["Player-1234-ABCDEF"].earned.waves_1.at'),null);assert.equal(h.get('MAMChroniclesDB.medals["Player-1234-ABCDEF"].earned.waves_2'),null);assert.equal(h.get('MAMChroniclesDB.medals["Player-1234-ABCDEF"].earned.hugs_3'),null);});
test('late-night and early-morning logins are counted from local time',()=>{const h=setup();h.run('local M=MAMChronicles.Medals; local base=os.time({year=2026,month=1,day=5,hour=2,min=0,sec=0}); for i=1,3 do MAMChronicles.Now=function() return 1790704800+i*100 end; MAMChronicles.EventStore:Append("session.login",{},{occurredAt=base+i*86400}) end; __late=M:EnsureCounts().lateLogin; local morning=os.time({year=2026,month=1,day=20,hour=6,min=0,sec=0}); MAMChronicles.Now=function() return 1790705500 end; MAMChronicles.EventStore:Append("session.login",{},{occurredAt=morning}); __early=M:EnsureCounts().earlyLogin');assert.equal(h.get('__late'),3);assert.equal(h.get('__early'),1);});
test('the medal catalogue is large, unique, and includes the Mom-themed set',()=>{const h=setup();h.run('local M=MAMChronicles.Medals; __n=#M:GetDefinitions(); __ok=true; local seen={}; for _,d in ipairs(M:GetDefinitions()) do if seen[d.id] then __ok=false end seen[d.id]=true end; __has=M:GetDefinition("wine_1")~=nil and M:GetDefinition("jumps_3")~=nil and M:GetDefinition("afk_1")~=nil and M:GetDefinition("late_1")~=nil');assert.equal(h.get('__n')>=100,true);assert.equal(h.get('__ok'),true);assert.equal(h.get('__has'),true);});
test('erasing history clears the counters',()=>{const h=setup();h.run('__hooks.JumpOrAscendStart(); MAMChronicles.Database:ClearHistory()');assert.equal(h.get('next(MAMChroniclesDB.counters)'),null);});
test('settings has a test toast button that cycles the toast kinds',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings"); MAMChronicles.Toast:Advance(60); MAMChronicles.Toast:Advance(60); local b=UI.testToastButton; b.scripts.OnClick(b); __one=MAMChronicles.Toast.title.text; MAMChronicles.Toast:Advance(60); MAMChronicles.Toast:Advance(60); b.scripts.OnClick(b); __two=MAMChronicles.Toast.title.text; MAMChronicles.Toast:Advance(60); MAMChronicles.Toast:Advance(60); b.scripts.OnClick(b); __three=MAMChronicles.Toast.title.text');assert.match(h.get('__one'),/Test/);assert.match(h.get('__two'),/Medal/);assert.match(h.get('__three'),/earned/);});
test('/mam toast sends a test toast and says why when it cannot',()=>{const h=setup();h.run('MAMChronicles.Toast:Advance(60); MAMChronicles.Toast:Advance(60)');h.slash('toast');assert.match(h.get('MAMChronicles.Toast.title.text'),/Test toast/);assert.equal(h.get('MAMChronicles.Toast.frame.shown'),true);h.run('MAMChronicles.Toast:Advance(60); MAMChronicles.Toast:Advance(60); MAMChronicles.SettingsPanel:ApplySetting("toastsEnabled",false)');h.slash('toast');assert.equal(h.get('MAMChronicles.Toast.frame.shown'),false);assert.equal(h.calls.printed.some(m=>/switched off/i.test(m)),true);});
