import test from 'node:test'; import assert from 'node:assert/strict'; import { createHarness } from './harness.js';
const files=['Core.lua','Database.lua','EventStore.lua','Statistics.lua','Export.lua'];
function setup(){const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.EventStore:Append("quest.completed",{questID=42,questName="Line\\nBreak"},{occurredAt=100}); MAMChronicles.EventStore:Append("loot.notable",{itemID=7,itemName="Epic",quality=4},{occurredAt=200})');return h;}
test('courier export is deterministic versioned and line safe',()=>{const h=setup();h.run('__a=MAMChronicles.Export:BuildCourierPayload(0,300); __b=MAMChronicles.Export:BuildCourierPayload(0,300)');const value=h.get('__a');assert.equal(value,h.get('__b'));assert.match(value,/^MAMCHRONICLES\/1/);assert.match(value,/questID=42/);assert.match(value,/itemID=7/);assert.ok(!value.includes('Line\nBreak'));assert.match(value,/COUNT\t2$/);});
test('exports exclude injected private fields',()=>{const h=setup();h.run('MAMChroniclesDB.events[1].payload.chat="WHISPER_MARKER"; MAMChroniclesDB.events[1].payload.battleTag="Private#1234"; MAMChroniclesDB.events[1].payload.path="C:/Account/Name"; MAMChroniclesDB.events[1].payload.gold=999; __out=MAMChronicles.Export:BuildCourierPayload(0,300)');const value=h.get('__out');for(const marker of ['WHISPER_MARKER','Private#1234','C:/Account/Name','999'])assert.ok(!value.includes(marker));});
test('diagnostics and human summary handle zero events without names',()=>{const h=setup();h.run('__diag=MAMChronicles.Export:BuildDiagnosticReport(); __human=MAMChronicles.Export:BuildHumanSummary(1000,2000)');assert.match(h.get('__diag'),/Schema: 1/);assert.ok(!h.get('__diag').includes('Mumtest'));assert.match(h.get('__human'),/Events recorded: 0/);});
test('diagnostics identify recent collector failures without leaking raw errors',()=>{const h=createHarness();h.load(['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua']);h.run('MAMChronicles:Boot(); MAMChronicles.EventStore.Append=function() error("C:/PRIVATE/Account Secret#1234") end; MAMChronicles:HandleEvent("PLAYER_LEVEL_UP",20); __diag=MAMChronicles.Export:BuildDiagnosticReport()');const value=h.get('__diag');assert.match(value,/Recent collector error: PLAYER_LEVEL_UP \(collector handler failed\)/);assert.ok(!value.includes('PRIVATE'));assert.ok(!value.includes('Secret#1234'));});
test('diagnostics name unavailable collector capabilities',()=>{const h=createHarness();h.load(['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua']);h.run('__mamFailEvent="ACHIEVEMENT_EARNED"; MAMChronicles:Boot(); __diag=MAMChronicles.Export:BuildDiagnosticReport()');assert.match(h.get('__diag'),/Unavailable collectors: ACHIEVEMENT_EARNED/);});
test('courier coordinates obey the current export privacy setting',()=>{const h=setup();h.run('MAMChronicles.EventStore:Append("memory.manual",{text="Here",mapID=1,x=0.25,y=0.75},{occurredAt=250}); MAMChroniclesDB.settings.recordCoordinates=false; __private=MAMChronicles.Export:BuildCourierPayload(0,300); MAMChroniclesDB.settings.recordCoordinates=true; __included=MAMChronicles.Export:BuildCourierPayload(0,300)');assert.ok(!h.get('__private').includes('\tx='));assert.ok(!h.get('__private').includes('\ty='));assert.match(h.get('__included'),/\tx=0\.25/);assert.match(h.get('__included'),/\ty=0\.75/);});
test('courier refuses views above two MiB and asks for a narrower range',()=>{const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); for i=1,5000 do MAMChronicles.EventStore:Append("memory.manual",{text=string.rep("x",512)},{occurredAt=1000+i}) end; __out,__err=MAMChronicles.Export:BuildCourierPayload(0,10000)');assert.equal(h.get('__out'),null);assert.match(h.get('__err'),/2 MiB.*narrow/i);});
