import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua','Theme.lua','Dashboard.lua','UI.lua','Launcher.lua'];
const saved=settings=>({schemaVersion:1,meta:{},settings,characters:{},sessions:{},events:{},eventIds:{},questCompletion:{},professionSnapshots:{},aggregates:{},diagnostics:{}});
function setup(options={}){const h=createHarness(options);h.load(files);h.run('MAMChronicles:Boot()');return h;}

test('launcher honours saved visibility and normalises its minimap angle',()=>{const h=setup({savedVariables:saved({showMinimapButton:true,ui:{minimapAngle:725}})});h.run('__angle=MAMChronicles.Launcher:SetAngle(725)');assert.equal(h.get('__angle'),5);assert.equal(h.get('MAMChroniclesDB.settings.ui.minimapAngle'),5);assert.equal(h.get('MAMChronicles.Launcher.button.shown'),true);});
test('launcher left click toggles Chronicle and right click opens settings',()=>{const h=setup();h.run('__toggles=0; __settings=0; MAMChronicles.UI.Toggle=function() __toggles=__toggles+1 end; MAMChronicles.SettingsPanel={Open=function() __settings=__settings+1 end}; MAMChronicles.Launcher:HandleClick("LeftButton"); MAMChronicles.Launcher:HandleClick("RightButton")');assert.equal(h.get('__toggles'),1);assert.equal(h.get('__settings'),1);});
test('launcher drag saves a bounded angle and reset restores the default',()=>{const h=setup();h.run('local b=MAMChronicles.Launcher.button; b.scripts.OnDragStart(b); b.scripts.OnUpdate(b); __dragged=MAMChroniclesDB.settings.ui.minimapAngle; b.scripts.OnDragStop(b); MAMChronicles.Launcher:ResetPosition(); __reset=MAMChroniclesDB.settings.ui.minimapAngle');assert.equal(h.get('__dragged')>=0&&h.get('__dragged')<360,true);assert.equal(h.get('__reset'),225);});
test('addon compartment callbacks are safe and share launcher actions',()=>{const h=setup();h.run('__toggles=0; MAMChronicles.UI.Toggle=function() __toggles=__toggles+1 end; MAMChronicles_AddonCompartmentClick("MAMChronicles","LeftButton"); MAMChronicles_AddonCompartmentEnter(Minimap); __tooltipShown=GameTooltip.shown; __tooltipLines=#GameTooltip.lines; MAMChronicles_AddonCompartmentLeave(); __tooltipHidden=not GameTooltip.shown; GameTooltip=nil; MAMChronicles_AddonCompartmentEnter(Minimap); MAMChronicles_AddonCompartmentLeave()');assert.equal(h.get('__toggles'),1);assert.equal(h.get('__tooltipShown'),true);assert.equal(h.get('__tooltipLines')>=3,true);assert.equal(h.get('__tooltipHidden'),true);});
test('hidden minimap setting keeps slash and compartment entry points available',()=>{const h=setup({savedVariables:saved({showMinimapButton:false})});assert.equal(h.get('MAMChronicles.Launcher.button.shown'),false);assert.equal(h.get('type(SlashCmdList.MAMCHRONICLES)'),'function');assert.equal(h.get('type(MAMChronicles_AddonCompartmentClick)'),'function');});
