import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Medals.lua','Counters.lua','Export.lua','Theme.lua','Toast.lua','Comms.lua','Dashboard.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
const key='Player-1234-ABCDEF';
const earned=id=>`MAMChroniclesDB.medals["${key}"].earned.${id}`;
const counter=name=>`(MAMChroniclesDB.counters["${key}"] or {}).${name}`;
const tally=name=>`MAMChroniclesDB.medalTallies["${key}"].${name}`;
const base=`
__vals={[201]="1,234",[302]="80"}
__cats={[4]={"Social",-1},[3]={"Quests",-1}}
__stats={[4]={{302,"Total waves"}},[3]={{201,"Quests completed"}}}
function GetStatisticsCategoryList() return {3,4} end
function GetCategoryInfo(id) return __cats[id][1],__cats[id][2] end
function GetCategoryNumAchievements(id) return #(__stats[id] or {}),0,0 end
function GetAchievementInfo(id,index) local s=__stats[id][index] return s[1],s[2] end
function GetStatistic(id) return __vals[id],false end
__hooks={}; __t=100; __actions={}; __falling=false; __merchant=false
function hooksecurefunc(a,b,c) if type(a)=="table" then __hooks[b]=c else __hooks[a]=b end end
function GetTime() return __t end
function GetActionInfo(slot) local a=__actions[slot] if a then return "item",a end end
function UseAction() end
function JumpOrAscendStart() end
function DoEmote() end
function RepairAllItems() end
function BuyMerchantItem() end
C_ChatInfo={PerformEmote=function() end}
C_MerchantFrame={SellAllJunkItems=function() end}
MerchantFrame={IsShown=function() return __merchant end}
C_Container={GetContainerItemInfo=function() return {itemID=__bagItem} end,UseContainerItem=function() end}
C_Item={GetItemNameByID=function(id) return ({[1]="Bottle of Red Wine"})[id] end}
function IsFalling() return __falling end
function UnitIsUnit(a,b) return a==b end
function UnitLevel() return __level or 12 end
function UnitRace() return "Human","Human",1 end`;
const forever='function GetBuildInfo() return "1.60.1","70009","Sep 2026",16001 end';
function setup(extra='',{scan=true}={}){const h=createHarness();h.load(files.slice(0,1));h.run(base+'\n'+extra);h.load(files.slice(1));h.run('MAMChronicles:Boot()'+(scan?'; MAMChronicles.AchievementStats:Scan()':''));return h;}
const login=(h,stamp,now)=>h.run(`MAMChronicles.Now=function() return ${now} end; MAMChronicles.EventStore:Append("session.login",{},{occurredAt=${stamp}})`);

test('availability follows the client and its level cap',()=>{const r=setup();assert.equal(r.get('MAMChronicles.Medals:Client()'),'retail');assert.equal(r.get('MAMChronicles.Medals:LevelCap()'),90);assert.equal(r.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("adventurer_5"))'),true);assert.equal(r.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("journey_1"))'),false);const f=setup(forever);assert.equal(f.get('MAMChronicles.Medals:Client()'),'forever');assert.equal(f.get('MAMChronicles.Medals:LevelCap()'),60);assert.equal(f.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("adventurer_4"))'),false);assert.equal(f.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("adventurer_3"))'),true);assert.equal(f.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("journey_1"))'),true);assert.equal(f.get('MAMChronicles.Medals:IsAvailable(MAMChronicles.Medals:GetDefinition("ready_for_core"))'),true);});
test('unavailable medals are hidden from progress and the possible total',()=>{const r=setup();r.run(`__ids={}; for _,e in ipairs(MAMChronicles.Medals:GetProgress("${key}")) do __ids[e.def.id]=true end; __s=MAMChronicles.Medals:GetSummary("${key}")`);assert.equal(r.get('__ids.journey_1'),null);assert.equal(r.get('__ids.adventurer_5'),true);const f=setup(forever);f.run(`__ids={}; for _,e in ipairs(MAMChronicles.Medals:GetProgress("${key}")) do __ids[e.def.id]=true end`);assert.equal(f.get('__ids.adventurer_4'),null);assert.equal(f.get('__ids.journey_1'),true);assert.equal(f.get('__ids.beta_mom'),true);assert.equal(r.get('__s.possible')<r.get('#MAMChronicles.Medals:GetDefinitions()'),true);});
test('emote hooks count tracked emotes once, whatever the spelling',()=>{const h=setup();h.run('__hooks.PerformEmote("sit"); __hooks.DoEmote("SIT"); __t=101; __hooks.PerformEmote("/Sit"); __t=102; __hooks.PerformEmote("dance"); __hooks.PerformEmote("blush")');assert.equal(h.get(counter('emote_sit')),2);assert.equal(h.get(counter('emote_dance')),1);assert.equal(h.get(counter('emote_blush')),null);assert.equal(h.get('MAMChronicles.Counters.hooked[1] ~= nil'),true);});
test('hugs, dances and kisses come from emote counters, not missing statistics',()=>{const h=setup();h.run('__seen={}; MAMChronicles.Medals:AddListener(function(d) if d then __seen[d.id]=true end end); for i=1,10 do __t=__t+1; __hooks.PerformEmote("hug") end');assert.equal(h.get('__seen.hugs_1'),true);assert.equal(h.get(earned('hugs_1')+'.retro'),null);});
test('waves use the larger of the statistic and the emote counter',()=>{const h=setup();assert.notEqual(h.get(earned('waves_1')+'.at'),null);assert.equal(h.get(earned('waves_2')),null);h.run('for i=1,100 do __t=__t+1; __hooks.PerformEmote("wave") end');assert.notEqual(h.get(earned('waves_2')+'.at'),null);});
test('new food and drink keywords classify whole words only',()=>{const h=setup();h.run('local C=MAMChronicles.Counters; local function has(list,x) for _,v in ipairs(list) do if v==x then return true end end return false end; __cheese=has(C:ClassifyItem("Aged Cheese"),"cheese"); __cookie=has(C:ClassifyItem("Gingerbread Cookies"),"cookie"); __pie=has(C:ClassifyItem("Apple Pie"),"pie"); __soup=has(C:ClassifyItem("Clam Chowder"),"soup"); __fish=has(C:ClassifyItem("Grilled Salmon"),"fish"); __juice=has(C:ClassifyItem("Fresh Apple Juice"),"juice"); __water=has(C:ClassifyItem("Refreshing Spring Water"),"water"); __no=#C:ClassifyItem("Watermelon Seed")+#C:ClassifyItem("Piecemeal Armor")');for(const k of ['__cheese','__cookie','__pie','__soup','__fish','__juice','__water'])assert.equal(h.get(k),true,k);assert.equal(h.get('__no'),0);});
test('vendor activity is counted: sales, purchases and repairs at an open merchant',()=>{const h=setup();h.run('__hooks.BuyMerchantItem(1); __hooks.SellAllJunkItems(); __bagItem=1; __hooks.UseContainerItem(0,1)');assert.equal(h.get(counter('purchases')),1);assert.equal(h.get(counter('sales')),1);h.run('__merchant=true; __hooks.UseContainerItem(0,1); __hooks.RepairAllItems()');assert.equal(h.get(counter('sales')),2);assert.equal(h.get(counter('repairs')),1);h.run('__merchant=false; __hooks.RepairAllItems()');assert.equal(h.get(counter('repairs')),1);});
test('groups, ready checks and equipment changes are counted with grace and debounce',()=>{const h=setup();h.fire('GROUP_JOINED');h.fire('GROUP_JOINED');h.run('__t=110');h.fire('GROUP_JOINED');assert.equal(h.get(counter('groups')),2);h.fire('GROUP_LEFT');assert.equal(h.get(counter('left')),1);h.fire('READY_CHECK_CONFIRM','player',true);h.fire('READY_CHECK_CONFIRM','player',true);h.fire('READY_CHECK_CONFIRM','party1',true);h.run('__t=200');h.fire('READY_CHECK_CONFIRM','player',false);assert.equal(h.get(counter('ready')),1);h.fire('PLAYER_ENTERING_WORLD');h.fire('PLAYER_EQUIPMENT_CHANGED',1,false);assert.equal(h.get(counter('outfits')),null);h.run('__t=__t+20');h.fire('PLAYER_EQUIPMENT_CHANGED',1,false);assert.equal(h.get(counter('outfits')),1);});
test('a death right after falling is recorded as a fall and earns Gravity\'s Favourite',()=>{const h=setup();h.run('__seen={}; MAMChronicles.Medals:AddListener(function(d) if d then __seen[d.id]=true end end); __falling=true; local c=MAMChronicles.Counters; c.ticker.scripts.OnUpdate(c.ticker,0.3); __falling=false; __t=__t+0.5');h.fire('PLAYER_DEAD');h.run('for i=#MAMChroniclesDB.events,1,-1 do local e=MAMChroniclesDB.events[i]; if e.type=="character.death" then __kind=e.payload.deathKind break end end');assert.equal(h.get('__kind'),'falling');assert.equal(h.get('__seen.gravity'),true);});
test('a death long after falling is not a fall',()=>{const h=setup();h.run('__falling=true; local c=MAMChronicles.Counters; c.ticker.scripts.OnUpdate(c.ticker,0.3); __falling=false; __t=__t+30');h.fire('PLAYER_DEAD');h.run('__kind="none"; for i=#MAMChroniclesDB.events,1,-1 do local e=MAMChroniclesDB.events[i]; if e.type=="character.death" then __kind=e.payload.deathKind or "none" break end end');assert.equal(h.get('__kind'),'none');});
test('tallies persist after old events are compacted away and are never double counted',()=>{const h=setup();h.run('local base=os.time({year=2026,month=1,day=5,hour=2}); for i=1,3 do MAMChronicles.Now=function() return 1790704800+i*100 end; MAMChronicles.EventStore:Append("session.login",{},{occurredAt=base+i*86400}) end');assert.equal(h.get(tally('lateLogin')),3);h.run('MAMChroniclesDB.events={}; MAMChroniclesDB.eventIds={}; MAMChronicles.Medals:Reset(); __late=MAMChronicles.Medals:EnsureCounts().lateLogin');assert.equal(h.get('__late'),3);});
test('login streaks and distinct weekends are tallied from local dates',()=>{const h=setup();h.run('local function at(m,d) return os.time({year=2026,month=m,day=d,hour=10}) end; __stamps={at(3,2),at(3,3),at(3,4),at(3,7),at(3,8),at(3,14),at(3,20)}');for(let i=1;i<=7;i++)login(h,`__stamps[${i}]`,1790704800+i*100);assert.equal(h.get(tally('bestStreak')),3);assert.equal(h.get(tally('streak')),1);assert.equal(h.get(tally('weekends')),2);assert.notEqual(h.get(earned('streak_1')+'.at'),null);assert.equal(h.get(earned('streak_2')),null);});
test('long sessions and quick relogins are tallied and the collector records session length',()=>{const h=setup();h.run('MAMChronicles.Now=function() return 1790705000 end; MAMChronicles.EventStore:Append("session.logout",{duration=20000},{occurredAt=1790705000})');assert.equal(h.get(tally('longestSession')),20000);assert.notEqual(h.get(earned('marathon_1')+'.at'),null);login(h,'1790705030',1790705100);assert.equal(h.get(tally('quickRelogs')),1);h.run('MAMChronicles.Now=function() return 1790705200 end');h.fire('PLAYER_LOGIN');h.run('MAMChronicles.Now=function() return 1790709800 end');h.fire('PLAYER_LOGOUT');assert.equal(h.get('type(MAMChroniclesDB.events[#MAMChroniclesDB.events].payload.duration)'),'number');});
test('dungeon visits are judged clean, learning experiences, and raid entries',()=>{const h=setup();const ev=(type,name,kind,now)=>h.run(`MAMChronicles.Now=function() return ${now} end; MAMChronicles.EventStore:Append("${type}",{instanceName="${name}",instanceType="${kind}"},{occurredAt=${now}})`);ev('instance.entered','A','party',1790706000);h.run('MAMChronicles.Now=function() return 1790706100 end; MAMChronicles.EventStore:Append("character.death",{zone="A"},{occurredAt=1790706100})');ev('instance.exited','A','party',1790706200);assert.equal(h.get(tally('cleanRuns')),null);assert.equal(h.get(tally('maxInstanceDeaths')),1);ev('instance.entered','B','party',1790706300);ev('instance.exited','B','party',1790706400);assert.equal(h.get(tally('cleanRuns')),1);ev('instance.entered','C','raid',1790706500);assert.equal(h.get(tally('raidEntries')),1);assert.notEqual(h.get(earned('raid_1')+'.at'),null);});
test('characters with the addon and character age feed their medals',()=>{const h=setup();h.run(`MAMChronicles.Database:RegisterCharacter("Other-Key",{name="Other",realm="R"}); MAMChroniclesDB.characters["${key}"].firstSeenAt=MAMChronicles:Now()-40*86400; MAMChronicles.Medals:Evaluate("test")`);assert.notEqual(h.get(earned('mom_of_many_1')+'.at'),null);assert.notEqual(h.get(earned('long_haul_1')+'.at'),null);assert.equal(h.get(earned('long_haul_2')),null);});
test('the WoW Forever medals are earned on Forever only',()=>{const prelude=forever+'\n__level=25\nfunction UnitRace() return "Skyborne","Skyborne",99 end';const f=setup(prelude,{scan:false});f.run('local M=MAMChronicles; M.Now=function() return 1790704800 end; M.EventStore:Append("session.login",{},{occurredAt=os.time({year=2026,month=10,day=20,hour=12})}); M.Now=function() return 1790704900 end; M.EventStore:Append("session.login",{},{occurredAt=os.time({year=2026,month=11,day=4,hour=12})}); MAMChroniclesDB.meta.createdAt=M:Now()-400*86400; M.AchievementStats:Scan()');for(const id of ['beta_mom','day_one','one_year','skyborne','journey_1','journey_2','adventurer_1'])assert.notEqual(f.get(earned(id)+'.at'),null,id);assert.equal(f.get(earned('journey_3')),null);assert.equal(f.get(earned('ready_for_core')),null);assert.equal(f.get(earned('adventurer_4')),null);const r=setup('__level=25',{scan:false});r.run('local M=MAMChronicles; M.Now=function() return 1790704800 end; M.EventStore:Append("session.login",{},{occurredAt=os.time({year=2026,month=10,day=20,hour=12})}); M.AchievementStats:Scan()');assert.equal(r.get(earned('beta_mom')),null);assert.equal(r.get(earned('journey_1')),null);});
test('reaching the Forever cap earns Ready for the Core',()=>{const f=setup(forever+'\n__level=60');assert.notEqual(f.get(earned('ready_for_core')+'.at'),null);assert.notEqual(f.get(earned('journey_5')+'.at'),null);});
test('the catalogue is large, unique, and every definition is well formed',()=>{const h=setup();h.run('local M=MAMChronicles.Medals; __n=#M:GetDefinitions(); __ok=true; local seen={}; for _,d in ipairs(M:GetDefinitions()) do if seen[d.id] or type(d.value)~="function" or type(d.target)~="number" or d.target<=0 or type(d.name)~="string" or type(d.description)~="string" or d.description:find("{n}",1,true) or (d.client~=nil and d.client~="forever" and d.client~="retail") then __ok=false end seen[d.id]=true end');assert.equal(h.get('__n')>=200,true);assert.equal(h.get('__ok'),true);});
test('diagnostics report the client, level cap, race token and installed hooks',()=>{const h=setup(forever);h.run('__d=MAMChronicles.Export:BuildDiagnosticReport()');assert.match(h.get('__d'),/Medals: client forever, level cap 60, race Human, hooks /);assert.match(h.get('__d'),/PerformEmote/);});
