import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Medals.lua','Export.lua','Theme.lua','Toast.lua','Dashboard.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
const api=`
__vals={[101]="12",[201]="1,234",[501]="30",[601]="5"}
__cats={[2]={"Deaths",-1},[3]={"Quests",-1},[5]={"Dungeons & Raids",-1}}
__stats={[2]={{101,"Total deaths"}},[3]={{201,"Quests completed"}},[5]={{501,"Total 5-player dungeons entered"},{601,"Total delves completed"}}}
function GetStatisticsCategoryList() return {2,3,5} end
function GetCategoryInfo(id) return __cats[id][1],__cats[id][2] end
function GetCategoryNumAchievements(id) return #(__stats[id] or {}),0,0 end
function GetAchievementInfo(id,index) local s=__stats[id][index] return s[1],s[2] end
function GetStatistic(id) return __vals[id],false end
function UnitLevel() return 12 end`;
const key='Player-1234-ABCDEF';
function setup({stats=true,scan=true}={}){const h=createHarness();h.load(files.slice(0,1));if(stats)h.run(api);h.load(files.slice(1));h.run('MAMChronicles:Boot(); __notified={}; MAMChronicles.Medals:AddListener(function(def,info) table.insert(__notified,{id=def and def.id,retro=info.retro,summary=info.summary,count=info.count,points=info.points}) end); MAMChronicles.EventStore:Append("character.death",{zone="Cave"},{occurredAt=1}); MAMChronicles.EventStore:Append("quest.completed",{questID=2,questName="Find Mum"},{occurredAt=2}); MAMChronicles.EventStore:Append("memory.manual",{text="Tea time"},{occurredAt=3})'+(scan?'; MAMChronicles.AchievementStats:Scan()':''));return h;}

test('medal definitions are unique, complete, and worth tier points',()=>{const h=setup({scan:false});h.run('local M=MAMChronicles.Medals; __seen={}; __ok=true; __n=0; for _,d in ipairs(M:GetDefinitions()) do __n=__n+1; if __seen[d.id] or type(d.name)~="string" or type(d.description)~="string" or type(d.target)~="number" or d.target<=0 or type(d.value)~="function" or (d.points~=10 and d.points~=25 and d.points~=50 and d.points~=100) then __ok=false end; __seen[d.id]=true end; __version=M.version');assert.equal(h.get('__ok'),true);assert.equal(h.get('__n')>=35,true);assert.equal(h.get('__version'),1);});
test('the first evaluation grants existing history silently as a baseline',()=>{const h=setup();assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.quest_machine_2.retro`),true);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.dungeon_regular_1.retro`),true);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.fresh_start.retro`),true);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.memory_keeper_1.retro`),true);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.quest_machine_3`),null);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].total`),65);assert.equal(h.get('MAMChronicles.EventStore:Count("medal.earned")'),0);assert.equal(h.get('#__notified'),1);assert.equal(h.get('__notified[1].summary'),true);assert.equal(h.get('__notified[1].count'),5);assert.equal(h.get('__notified[1].points'),65);});
test('nothing is awarded until statistics have been read or ruled out',()=>{const h=setup({scan:false});h.run('__early=MAMChronicles.Medals:Evaluate("boot")');assert.equal(h.get('#__early'),0);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"]`),null);});
test('without statistics support the baseline still completes from Chronicle events',()=>{const h=setup({stats:false});assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.fresh_start.retro`),true);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.quest_machine_1`),null);});
test('crossing a threshold after the baseline earns a live medal, a timeline event, and a notification',()=>{const h=setup();h.run('__notified={}; __vals[201]="1,600"; MAMChronicles.AchievementStats:Scan()');assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.quest_machine_3.retro`),null);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].total`),115);assert.equal(h.get('#__notified'),1);assert.equal(h.get('__notified[1].id'),'quest_machine_3');assert.equal(h.get('__notified[1].retro'),false);assert.equal(h.get('MAMChronicles.EventStore:Count("medal.earned")'),1);});
test('Chronicle events earn medals as they happen and counters stay incremental',()=>{const h=setup();h.run('__notified={}; for i=1,9 do MAMChronicles.EventStore:Append("memory.manual",{text="Memory "..i},{occurredAt=10+i}) end');assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.memory_keeper_2.points`),25);assert.equal(h.get('#__notified'),1);assert.equal(h.get('__notified[1].id'),'memory_keeper_2');});
test('death context signals earn the humorous medals',()=>{const h=setup();h.run('__notified={}; MAMChronicles.Now=function() return 1790704900 end; MAMChronicles.EventStore:Append("character.death",{zone="Cliff",deathKind="falling"},{occurredAt=50}); MAMChronicles.Now=function() return 1790705000 end; MAMChronicles.EventStore:Append("character.death",{zone="Murloc Cove"},{occurredAt=60})');assert.notEqual(h.get(`MAMChroniclesDB.medals["${key}"].earned.gravity.at`),null);assert.notEqual(h.get(`MAMChroniclesDB.medals["${key}"].earned.murloc_magnet.at`),null);});
test('evaluating again never awards the same medal twice',()=>{const h=setup();h.run('__notified={}; MAMChronicles.Medals:Evaluate("again"); MAMChronicles.Medals:Evaluate("again")');assert.equal(h.get('#__notified'),0);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].total`),65);});
test('progress reports current value, target and earned state',()=>{const h=setup();h.run(`__p={}; for _,e in ipairs(MAMChronicles.Medals:GetProgress("${key}")) do __p[e.def.id]=e end`);assert.equal(h.get('__p.quest_machine_3.current'),1234);assert.equal(h.get('__p.quest_machine_3.target'),1500);assert.equal(h.get('__p.quest_machine_3.earned'),null);assert.notEqual(h.get('__p.quest_machine_2.earned'),null);});
test('summary totals the Mom Money and medal count',()=>{const h=setup();h.run(`__s=MAMChronicles.Medals:GetSummary("${key}")`);assert.equal(h.get('__s.total'),65);assert.equal(h.get('__s.count'),5);assert.equal(h.get('__s.possible>=35'),true);});
test('erasing Chronicle history resets medals to a fresh silent baseline',()=>{const h=setup();h.run('MAMChronicles.Database:ClearHistory()');assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].earned.memory_keeper_1`),null);assert.equal(h.get(`MAMChroniclesDB.medals["${key}"].total`)<65,true);assert.equal(h.get('MAMChronicles.EventStore:Count("medal.earned")'),0);});
test('medal timeline events have a label, colour and filter',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; __n,__c=T:DescribeType("medal.earned"); __has=false; for _,f in ipairs(MAMChronicles.UI.filters) do if f=="Medals" then __has=true end end');assert.equal(h.get('__n'),'Medal');assert.equal(h.get('__has'),true);});
test('the dashboard reports Mom Money and shows it in the month card',()=>{const h=setup();h.run('__m=MAMChronicles.Dashboard:Build(); MAMChronicles.UI:Show(); MAMChronicles.UI:SetActiveTab("Home")');assert.equal(h.get('__m.medals.total'),65);assert.equal(h.get('__m.medals.count'),5);assert.match(h.get('MAMChronicles.Dashboard.monthBody.text'),/Mom Money 65/);});
test('the Medals tab lists every medal with earned ones first and shows the money total',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Medals"); __rows=#UI.medalRows; __defs=#MAMChronicles.Medals:GetDefinitions(); __first=UI.medalRows[1].name.text; __header=UI.medalHeader.text; __shown=UI.medalsArea.scroll.shown');assert.equal(h.get('__rows'),h.get('__defs'));assert.match(h.get('__header'),/65/);assert.equal(h.get('__shown'),true);const first=h.get('__first');assert.equal(['Fresh Start','Memory Keeper I','Quest Machine I','Quest Machine II','Dungeon Regular I'].includes(first),true);h.run('MAMChronicles.UI:SetActiveTab("Home")');assert.equal(h.get('MAMChronicles.UI.medalsArea.scroll.shown'),false);});
