import test from 'node:test'; import assert from 'node:assert/strict';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os'; import { join, resolve } from 'node:path'; import { spawnSync } from 'node:child_process'; import { createHash } from 'node:crypto';
import { addonRoot, repositoryRoot } from './harness.js';
const packageScript=resolve(repositoryRoot,'scripts','package-mam-chronicles.ps1'); const installScript=resolve(repositoryRoot,'scripts','install-mam-chronicles.ps1');
const run=args=>spawnSync('pwsh',['-NoProfile',...args],{cwd:repositoryRoot,encoding:'utf8'});
const expectedFiles=['AchievementStats.lua','Medals.lua','Counters.lua','Toast.lua','Comms.lua','Collectors.lua','Core.lua','Dashboard.lua','Database.lua','EventStore.lua','Export.lua','LICENSE.txt','CHANGELOG.md','Launcher.lua','MAMChronicles.toc','MAMChroniclesIcon.tga','README.md','SettingsPanel.lua','Statistics.lua','Theme.lua','UI.lua'].sort();
const esc=v=>v.replaceAll("'","''");
function client(root,name='_retail_'){const value=join(root,name);mkdirSync(join(value,'Interface','AddOns'),{recursive:true});return value;}
function install({clientRoot,backupRoot,sourceRoot=addonRoot,running=false,fail=false}){const command=`& '${esc(installScript)}' -ClientRoot '${esc(clientRoot)}' -BackupRoot '${esc(backupRoot)}' -SourceRoot '${esc(sourceRoot)}' -ProcessProbe { $${running?'true':'false'} } -BeforeActivate { ${fail?'throw \'simulated activation failure\'':''} }`;return run(['-Command',command]);}
test('package archive contains only the exact addon allowlist with source-identical files',()=>{const root=mkdtempSync(join(tmpdir(),'mam-package-'));const output=join(root,'dist');const result=run(['-File',packageScript,'-OutputRoot',output]);assert.equal(result.status,0,`${result.stdout}\n${result.stderr}`);assert.match(result.stdout,/SHA256: [A-F0-9]{64}/);const archive=join(output,'MAMChronicles-0.2.0-alpha9.zip');assert.equal(existsSync(archive),true);const extract=join(root,'extract');assert.equal(run(['-Command',`Expand-Archive -LiteralPath '${esc(archive)}' -DestinationPath '${esc(extract)}'`]).status,0);const names=expectedFiles;assert.deepEqual(readdirSync(join(extract,'MAMChronicles')).sort(),names);for(const name of names){const digest=path=>createHash('sha256').update(readFileSync(path)).digest('hex');assert.equal(digest(join(extract,'MAMChronicles',name)),digest(join(addonRoot,name)),`${name} differs from source`);}});
test('installer supports Retail and Forever and refuses a running client',()=>{for(const name of ['_retail_','_classic_beta_']){const root=mkdtempSync(join(tmpdir(),'mam-client-'));const target=client(root,name);const result=install({clientRoot:target,backupRoot:join(root,'backup')});assert.equal(result.status,0,`${result.stdout}\n${result.stderr}`);const installed=join(target,'Interface','AddOns','MAMChronicles');assert.deepEqual(readdirSync(installed).sort(),expectedFiles);const digest=path=>createHash('sha256').update(readFileSync(path)).digest('hex');for(const file of expectedFiles)assert.equal(digest(join(installed,file)),digest(join(addonRoot,file)),`${file} differs from source`);}const root=mkdtempSync(join(tmpdir(),'mam-running-'));const target=client(root);const denied=install({clientRoot:target,backupRoot:join(root,'backup'),running:true});assert.notEqual(denied.status,0);assert.match(`${denied.stdout}${denied.stderr}`,/running/i);});
test('installer validates manifest and preserves unrelated addons',()=>{const root=mkdtempSync(join(tmpdir(),'mam-invalid-'));const target=client(root);const unrelated=join(target,'Interface','AddOns','KeepMe');mkdirSync(unrelated);writeFileSync(join(unrelated,'keep.txt'),'yes');const source=join(root,'source');cpSync(addonRoot,source,{recursive:true});const toc=join(source,'MAMChronicles.toc');writeFileSync(toc,readFileSync(toc,'utf8').replace(/^## Interface:.*$/mu,'## Interface: 99999'));const result=install({clientRoot:target,backupRoot:join(root,'backup'),sourceRoot:source});assert.notEqual(result.status,0);assert.equal(readFileSync(join(unrelated,'keep.txt'),'utf8'),'yes');});
test('installer backs up and rolls back a failed activation',()=>{const root=mkdtempSync(join(tmpdir(),'mam-rollback-'));const target=client(root);const addon=join(target,'Interface','AddOns','MAMChronicles');mkdirSync(addon);writeFileSync(join(addon,'old.txt'),'old');const backup=join(root,'backup');const failed=install({clientRoot:target,backupRoot:backup,fail:true});assert.notEqual(failed.status,0);assert.equal(readFileSync(join(addon,'old.txt'),'utf8'),'old');assert.equal(readdirSync(backup).filter(x=>x.endsWith('.zip')).length,1);});
test('installer rejects a backup root equal to the client root',()=>{const root=mkdtempSync(join(tmpdir(),'mam-backup-root-'));const target=client(root);const result=install({clientRoot:target,backupRoot:target});assert.notEqual(result.status,0);assert.match(`${result.stdout}${result.stderr}`,/outside/i);});
