import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Export.lua','Theme.lua','Dashboard.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
function saved(settings){return {schemaVersion:1,meta:{},settings,characters:{},sessions:{},events:{},eventIds:{},questCompletion:{},professionSnapshots:{},aggregates:{},diagnostics:{}};}
function setup(options={},prelude=''){const h=createHarness(options);h.load(files.slice(0,1));if(prelude)h.run(prelude);h.load(files.slice(1));h.run('MAMChronicles:Boot()');return h;}

test('new appearance and alert settings have safe defaults',()=>{const h=setup();assert.equal(h.get('MAMChroniclesDB.settings.windowAlpha'),1);assert.equal(h.get('MAMChroniclesDB.settings.theme'),'midnight');assert.equal(h.get('MAMChroniclesDB.settings.toastsEnabled'),true);assert.equal(h.get('MAMChroniclesDB.settings.toastSound'),false);assert.equal(h.get('MAMChroniclesDB.settings.announceMedals'),true);assert.equal(h.get('MAMChroniclesDB.settings.announceGuildChat'),false);assert.equal(h.get('MAMChroniclesDB.settings.receiveGuildAlerts'),true);});
test('malformed appearance and alert settings are repaired',()=>{const h=setup({savedVariables:saved({windowAlpha:'clear',theme:'neon',toastsEnabled:'yes',toastSound:1,announceMedals:null,announceGuildChat:'no',receiveGuildAlerts:{}})});assert.equal(h.get('MAMChroniclesDB.settings.windowAlpha'),1);assert.equal(h.get('MAMChroniclesDB.settings.theme'),'midnight');assert.equal(h.get('MAMChroniclesDB.settings.toastsEnabled'),true);assert.equal(h.get('MAMChroniclesDB.settings.toastSound'),false);assert.equal(h.get('MAMChroniclesDB.settings.announceMedals'),true);assert.equal(h.get('MAMChroniclesDB.settings.announceGuildChat'),false);assert.equal(h.get('MAMChroniclesDB.settings.receiveGuildAlerts'),true);});
test('out-of-range window transparency is clamped',()=>{const h=setup({savedVariables:saved({windowAlpha:0.01})});assert.equal(h.get('MAMChroniclesDB.settings.windowAlpha'),0.3);const g=setup({savedVariables:saved({windowAlpha:9})});assert.equal(g.get('MAMChroniclesDB.settings.windowAlpha'),1);});
test('theme presets recolour the palette in place and fall back to midnight',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; __ref=T.colors.bg; __before=T.colors.bg[1]; T:ApplyPreset("parchment"); __same=(__ref==T.colors.bg); __after=T.colors.bg[1]; __name=T.current; T:ApplyPreset("neon"); __fallback=T.current; __back=T.colors.bg[1]');assert.equal(h.get('__same'),true);assert.equal(h.get('__after')>h.get('__before'),true);assert.equal(h.get('__name'),'parchment');assert.equal(h.get('__fallback'),'midnight');assert.equal(h.get('__back'),h.get('__before'));});
test('every preset is a complete valid palette',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; __ok=true; __count=0; for name,preset in pairs(T.presets) do __count=__count+1; for key in pairs(T.colors) do local c=preset[key]; if type(c)~="table" then __ok=false else for i=1,4 do if type(c[i])~="number" or c[i]<0 or c[i]>1 then __ok=false end end end end end');assert.equal(h.get('__ok'),true);assert.equal(h.get('__count'),4);});
test('the saved theme is applied when the addon boots',()=>{const h=setup({savedVariables:saved({theme:'crimson'})});assert.equal(h.get('MAMChronicles.Theme.current'),'crimson');assert.equal(h.get('MAMChronicles.Theme.colors.accent[1]'),h.get('MAMChronicles.Theme.presets.crimson.accent[1]'));});
test('window transparency changes the background alpha immediately',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Create(); __ok=UI:SetSetting("windowAlpha",0.6); __fill=UI.bgFill.color[4]; __back=UI.frame.backdropColor[4]; UI:SetSetting("windowAlpha",0.05); __low=UI.bgFill.color[4]; UI:SetSetting("windowAlpha",7); __high=UI.bgFill.color[4]');assert.equal(h.get('__ok'),true);assert.equal(h.get('__fill'),0.6);assert.equal(h.get('__back'),0.6);assert.equal(h.get('__low'),0.3);assert.equal(h.get('__high'),1);});
test('theme setting accepts only known presets and boolean alert toggles reject junk',()=>{const h=setup();h.run('local P=MAMChronicles.SettingsPanel; __t1=P:ApplySetting("theme","slate"); __t2=P:ApplySetting("theme","neon"); __a=P:ApplySetting("toastsEnabled",false); __b=P:ApplySetting("announceMedals",false); __c=P:ApplySetting("announceGuildChat",true); __d=P:ApplySetting("receiveGuildAlerts",false); __e=P:ApplySetting("toastSound",true)');assert.equal(h.get('__t1'),true);assert.equal(h.get('__t2'),false);assert.equal(h.get('MAMChroniclesDB.settings.theme'),'slate');assert.equal(h.get('MAMChroniclesDB.settings.toastsEnabled'),false);assert.equal(h.get('MAMChroniclesDB.settings.announceMedals'),false);assert.equal(h.get('MAMChroniclesDB.settings.announceGuildChat'),true);assert.equal(h.get('MAMChroniclesDB.settings.receiveGuildAlerts'),false);assert.equal(h.get('MAMChroniclesDB.settings.toastSound'),true);});
test('settings page offers theme buttons, a transparency slider, and grouped toggles',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings")');assert.equal(h.get('#MAMChronicles.UI.themeButtons'),4);assert.equal(h.get('MAMChronicles.UI.alphaSlider ~= nil'),true);for(const key of ['enabled','recordQuestAccepts','recordCoordinates','showMinimapButton','recordStatistics','recordGoldStatistics','toastsEnabled','toastSound','announceMedals','announceGuildChat','receiveGuildAlerts'])assert.equal(h.get(`MAMChronicles.UI.settingChecks.${key} ~= nil`),true,key);assert.equal(h.get('MAMChronicles.UI.settingsArea.scroll.shown'),true);h.run('MAMChronicles.UI:SetActiveTab("Home")');assert.equal(h.get('MAMChronicles.UI.settingsArea.scroll.shown'),false);});
test('transparency slider drives the saved setting and the live background',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings"); UI.alphaSlider:SetValue(40)');assert.equal(h.get('MAMChroniclesDB.settings.windowAlpha'),0.6);assert.equal(h.get('MAMChronicles.UI.bgFill.color[4]'),0.6);});
test('choosing a theme saves it and Apply reloads the interface once',()=>{const h=setup({},'__reloads=0; function ReloadUI() __reloads=__reloads+1 end');h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings"); UI.themeButtons[2].scripts.OnClick(UI.themeButtons[2]); __saved=MAMChroniclesDB.settings.theme; __beforeApply=__reloads; UI.applyThemeButton.scripts.OnClick(UI.applyThemeButton)');assert.equal(h.get('__saved'),'parchment');assert.equal(h.get('__beforeApply'),0);assert.equal(h.get('__reloads'),1);});
test('settings checkboxes follow changes made elsewhere',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings"); MAMChronicles.SettingsPanel:ApplySetting("toastsEnabled",false); UI:SyncSettingsControls(); __off=UI.settingChecks.toastsEnabled.checked; MAMChronicles.SettingsPanel:ApplySetting("toastsEnabled",true); UI:SyncSettingsControls(); __on=UI.settingChecks.toastsEnabled.checked');assert.equal(h.get('__off'),false);assert.equal(h.get('__on'),true);});
test('the settings page scrolls when it is taller than the window',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Settings"); UI:ApplyLayout(620,440); __range=UI.settingsArea.slider.maxValue; UI.settingsArea.scroll.scripts.OnMouseWheel(UI.settingsArea.scroll,-1); __scroll=UI.settingsArea.scroll:GetVerticalScroll()');assert.equal(h.get('__range')>0,true);assert.equal(h.get('__scroll')>0,true);});
