import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
function setup(prelude='',options={}){const h=createHarness(options);h.load(files.slice(0,1));h.run(prelude);h.load(files.slice(1));h.run('MAMChronicles:Boot()');return h;}
const modern='__registered=0; __added=0; __opened=nil; Settings={RegisterCanvasLayoutCategory=function(panel,name) __panelName=name return {ID=7,GetID=function(self) return self.ID end} end,RegisterAddOnCategory=function(category) __added=__added+1 end,OpenToCategory=function(id) __opened=id end}';
const popups='StaticPopupDialogs={}; YES="Yes"; NO="No"; __popup=nil; StaticPopup_Show=function(name) __popup=name return {} end';

test('settings panel prefers modern registration and opens its category',()=>{const h=setup(modern);h.run('MAMChronicles.SettingsPanel:Open()');assert.equal(h.get('__added'),1);assert.equal(h.get('__panelName'),'Moms Against Magic Chronicles');assert.equal(h.get('__opened'),7);});
test('settings panel falls back to legacy registration and degrades with neither API',()=>{const legacy=setup('__legacy=0; __legacyOpen=0; InterfaceOptions_AddCategory=function() __legacy=__legacy+1 end; InterfaceOptionsFrame_OpenToCategory=function() __legacyOpen=__legacyOpen+1 end');legacy.run('MAMChronicles.SettingsPanel:Open()');assert.equal(legacy.get('__legacy'),1);assert.equal(legacy.get('__legacyOpen'),2);const none=setup();none.run('__open=MAMChronicles.SettingsPanel:Open()');assert.equal(none.get('MAMChronicles.UI.activeTab'),'Settings');});
test('showMinimapButton setting immediately updates launcher visibility',()=>{const h=setup();h.run('__bad=MAMChronicles.SettingsPanel:ApplySetting("bogus",true); MAMChronicles.SettingsPanel:ApplySetting("showMinimapButton",false)');assert.equal(h.get('__bad'),false);assert.equal(h.get('MAMChronicles.Launcher.button.shown'),false);assert.equal(h.get('MAMChroniclesDB.settings.showMinimapButton'),false);h.run('MAMChronicles.SettingsPanel:ApplySetting("showMinimapButton",true)');assert.equal(h.get('MAMChronicles.Launcher.button.shown'),true);});
test('reset actions call the window and launcher reset contracts',()=>{const h=setup();h.run('__w=0; __m=0; MAMChronicles.UI.ResetWindow=function() __w=__w+1 end; MAMChronicles.Launcher.ResetPosition=function() __m=__m+1 end; MAMChronicles.SettingsPanel:ResetWindow(); MAMChronicles.SettingsPanel:ResetMinimap()');assert.equal(h.get('__w'),1);assert.equal(h.get('__m'),1);});
test('erase request requires popup confirmation and preserves settings',()=>{const h=setup(popups);h.run('MAMChroniclesDB.settings.showMinimapButton=false; MAMChroniclesDB.events.fake={id="fake"}; __ok=MAMChronicles.SettingsPanel:RequestEraseHistory()');assert.equal(h.get('__ok'),true);assert.equal(h.get('__popup'),'MAMCHRONICLES_ERASE_HISTORY');assert.notEqual(h.get('MAMChroniclesDB.events.fake'),null);h.run('StaticPopupDialogs.MAMCHRONICLES_ERASE_HISTORY.OnAccept()');assert.equal(h.get('MAMChroniclesDB.events.fake'),null);assert.equal(h.get('MAMChroniclesDB.settings.showMinimapButton'),false);});
test('erase control is disabled when confirmation APIs are absent',()=>{const h=setup();h.run('MAMChroniclesDB.events.fake={id="fake"}; __ok=MAMChronicles.SettingsPanel:RequestEraseHistory()');assert.equal(h.get('__ok'),false);assert.notEqual(h.get('MAMChroniclesDB.events.fake'),null);});
test('first-run local-only welcome prints once',()=>{const h=setup();const count=()=>h.calls.printed.filter(m=>/stays on this computer/.test(m)).length;assert.equal(count(),1);assert.equal(h.get('MAMChroniclesDB.settings.welcomeVersion'),'personal-chronicle-v1');h.run('MAMChronicles.booted=false; MAMChronicles:Boot()');assert.equal(count(),1);});
