import test from 'node:test';
import assert from 'node:assert/strict';
import { createHarness } from './harness.js';

const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','AchievementStats.lua','Export.lua','Theme.lua','UI.lua','Launcher.lua','SettingsPanel.lua'];
function setup(){const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.EventStore:Append("character.death",{zone="Cave"},{occurredAt=1}); MAMChronicles.EventStore:Append("quest.completed",{questID=2,questName="Find Mum"},{occurredAt=2}); MAMChronicles.EventStore:Append("memory.manual",{text="Tea time"},{occurredAt=3})');return h;}

test('theme palette is made of valid colour components and exposes hex strings',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; __ok=true; for name,c in pairs(T.colors) do for i=1,4 do if type(c[i])~="number" or c[i]<0 or c[i]>1 then __ok=false end end end; __gold=T:Hex(T.colors.gold); __white=T:Hex({1,1,1,1})');assert.equal(h.get('__ok'),true);assert.match(h.get('__gold'),/^[0-9a-f]{6}$/);assert.equal(h.get('__white'),'ffffff');});
test('flat buttons highlight on hover, restore on leave, and dim when disabled',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; local b=T:Button(UIParent,"Go",100,24); b:SetText("Go"); b.scripts.OnEnter(b); __hover=b.backdropColor[1]; b.scripts.OnLeave(b); __rest=b.backdropColor[1]; T:SetEnabled(b,false); __dim=b.label.textColor[1]; T:SetEnabled(b,true); __lit=b.label.textColor[1]; __hoverRef=T.colors.hover[1]; __raisedRef=T.colors.raised[1]; __disRef=T.colors.disabled[1]; __textRef=T.colors.text[1]');assert.equal(h.get('__hover'),h.get('__hoverRef'));assert.equal(h.get('__rest'),h.get('__raisedRef'));assert.equal(h.get('__dim'),h.get('__disRef'));assert.equal(h.get('__lit'),h.get('__textRef'));});
test('selected tabs show the accent underline and gold text',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; local b=T:Tab(UIParent,"Chronicle",110,28); T:SetSelected(b,true); __on=b.underline.shown; __gold=b.label.textColor[1]; T:SetSelected(b,false); __off=b.underline.shown; __goldRef=T.colors.gold[1]');assert.equal(h.get('__on'),true);assert.equal(h.get('__gold'),h.get('__goldRef'));assert.equal(h.get('__off'),false);});
test('event types map to a readable label and a colour',()=>{const h=setup();h.run('local T=MAMChronicles.Theme; __d,__dc=T:DescribeType("character.death"); __q=T:DescribeType("quest.completed"); __m=T:DescribeType("memory.manual"); __x,__xc=T:DescribeType("something.new"); __death=T.kindColors.death[1]; __muted=T.colors.muted[1]');assert.equal(h.get('__d'),'Death');assert.equal(h.get('__q'),'Quest');assert.equal(h.get('__m'),'Memory');assert.equal(h.get('__x'),'Something new');assert.equal(h.get('__dc[1]'),h.get('__death'));assert.equal(h.get('__xc[1]'),h.get('__muted'));});
test('main window uses the flat dark style and relative layout',()=>{const h=setup();h.run('MAMChronicles.UI:Create()');assert.match(h.get('MAMChronicles.UI.frame.backdrop.bgFile'),/WHITE8x8/);assert.equal(h.get('MAMChronicles.UI.frame.backdropColor[4]')>=0.9,true);assert.equal(h.get('MAMChronicles.UI.titleBarIcon ~= nil'),true);});
test('timeline rows show a colour-coded type label and a time column',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); __first=UI.rowButtons[1]; __kind=__first.kindText.text; __kindColor=__first.kindText.textColor[1]; __time=__first.timeText.text; __label=UI.rowPool[1].text; __stripe=__first.stripe.color[1]; __memory=MAMChronicles.Theme.kindColors.memory[1]');assert.equal(h.get('__kind'),'Memory');assert.equal(h.get('__kindColor'),h.get('__memory'));assert.equal(h.get('__stripe'),h.get('__memory'));assert.equal(typeof h.get('__time'),'string');assert.match(h.get('__label'),/Tea time/);});
test('row height grows with the window but stays between 13 and 20 pixels',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Create(); __small=UI:LayoutRows(300); __mid=UI:LayoutRows(480); __big=UI:LayoutRows(2000)');assert.equal(h.get('__small'),13);assert.equal(h.get('__mid'),16);assert.equal(h.get('__big'),20);});
test('statistics tab colours group headings with the theme gold',()=>{const h=createHarness();h.load(files);h.run('__vals={[101]="12"}; __cats={[2]={"Deaths",-1}}; __stats={[2]={{101,"Total deaths"}}}; function GetStatisticsCategoryList() return {2} end; function GetCategoryInfo(id) return __cats[id][1],__cats[id][2] end; function GetCategoryNumAchievements(id) return 1,0,0 end; function GetAchievementInfo(id,i) return 101,"Total deaths" end; function GetStatistic(id) return __vals[id],false end; MAMChronicles:Boot(); MAMChronicles.AchievementStats:Scan(); MAMChronicles.UI:Show(); MAMChronicles.UI:SetActiveTab("Statistics")');const text=h.get('MAMChronicles.UI.content.text');assert.match(text,/\|cff[0-9a-f]{6}Lifetime statistics\|r/);assert.match(text,/\|cff[0-9a-f]{6}Deaths and combat\|r/);assert.match(text,/Total deaths 12/);});
test('tooltips are chained onto button hover so the highlight survives',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); local b=UI.filterButton; b.scripts.OnEnter(b); __lines=#GameTooltip.lines; __hover=b.backdropColor[1]; b.scripts.OnLeave(b); __rest=b.backdropColor[1]; __tip=GameTooltip.shown; __hoverRef=MAMChronicles.Theme.colors.hover[1]; __raisedRef=MAMChronicles.Theme.colors.raised[1]');assert.equal(h.get('__lines')>=2,true);assert.equal(h.get('__hover'),h.get('__hoverRef'));assert.equal(h.get('__rest'),h.get('__raisedRef'));assert.equal(h.get('__tip'),false);});
