import test from 'node:test'; import assert from 'node:assert/strict'; import { createHarness } from './harness.js';
const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua','UI.lua'];
function setup(){const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.EventStore:Append("character.death",{zone="Cave"},{occurredAt=1}); MAMChronicles.EventStore:Append("quest.completed",{questID=2,questName="Find Mum"},{occurredAt=2}); MAMChronicles.EventStore:Append("memory.manual",{text="Tea time"},{occurredAt=3})');return h;}
test('UI exposes four tabs and a fixed row pool',()=>{const h=setup();h.run('__a=MAMChronicles.UI:Create(); __same=(__a==MAMChronicles.UI:Create())');assert.equal(h.get('#MAMChronicles.UI.tabs'),4);assert.equal(h.get('MAMChronicles.UI.tabs[1]'),'Chronicle');assert.equal(h.get('MAMChronicles.UI.tabs[4]'),'Diagnostics');assert.equal(h.get('#MAMChronicles.UI.rowPool'),30);assert.equal(h.get('__same'),true);});
test('UI provides an operational bottom-right resize handle',()=>{const h=setup();h.run('MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.resizeHandle ~= nil'),true);assert.equal(h.get('type(MAMChronicles.UI.resizeHandle.scripts.OnMouseDown)'), 'function');assert.equal(h.get('type(MAMChronicles.UI.resizeHandle.scripts.OnMouseUp)'), 'function');});
test('timeline model searches and filters newest first',()=>{const h=setup();h.run('__q=MAMChronicles.UI:BuildTimeline({filter="Quests",search="mum"}); __all=MAMChronicles.UI:BuildTimeline({filter="All"})');assert.equal(h.get('#__q'),1);assert.equal(h.get('__q[1].type'),'quest.completed');assert.equal(h.get('__all[1].type'),'memory.manual');});
test('slash commands dispatch memories exports diagnostics and help',()=>{const h=setup();h.slash('remember A lovely run');assert.equal(h.get('MAMChronicles.EventStore:Count("memory.manual")'),2);h.slash('export');assert.match(h.get('MAMChronicles.UI.copyText'),/^MAMCHRONICLES\/1/);h.slash('diag');assert.match(h.get('MAMChronicles.UI.copyText'),/Diagnostics/);h.slash('nonsense');assert.equal(h.get('MAMChronicles.UI.lastMessage'),'Commands: /mam, remember, stats, export, diag, help');});
test('copy views hide timeline controls that could intercept text selection',()=>{const h=setup();h.run('MAMChronicles.UI.activeTab="Chronicle"; MAMChronicles.UI:Show(); __before=MAMChronicles.UI.rowButtons[1].shown; MAMChronicles.UI:ShowCopy("copy me"); __after=MAMChronicles.UI.rowButtons[1].shown; __copyShown=MAMChronicles.UI.copyBox.shown');assert.equal(h.get('__before'),true);assert.equal(h.get('__after'),false);assert.equal(h.get('__copyShown'),true);});
test('settings update validates supported values',()=>{const h=setup();h.run('__ok=MAMChronicles.UI:SetSetting("recordCoordinates",false); __bad=MAMChronicles.UI:SetSetting("secret",true)');assert.equal(h.get('__ok'),true);assert.equal(h.get('MAMChroniclesDB.settings.recordCoordinates'),false);assert.equal(h.get('__bad'),false);});
test('settings display the persisted Legendary-only loot threshold',()=>{const h=setup();h.run('MAMChroniclesDB.settings.notableQuality=5; MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.qualityButton and MAMChronicles.UI.qualityButton.text'),'Loot: Legendary only');});
test('timeline paging reaches entries beyond the fixed row pool',()=>{const h=setup();h.run('for i=1,35 do MAMChronicles.EventStore:Append("memory.manual",{text="Page "..i},{occurredAt=100+i}) end; MAMChronicles.UI.timelineOffset=30; __page=MAMChronicles.UI:GetVisibleTimeline()');assert.equal(h.get('#__page'),8);assert.equal(h.get('__page[1].payload.text'),'Page 5');});
test('current month range begins on calendar day one',()=>{const h=setup();h.run('__from,__to=MAMChronicles.UI:GetCurrentMonthRange()');assert.equal(h.get('os.date("%d",__from)'),'01');assert.equal(h.get('__to'),1790704800);});
test('event details expose useful allowlisted fields',()=>{const h=setup();h.run('__details=MAMChronicles.UI:FormatEventDetails(MAMChroniclesDB.events[2])');assert.match(h.get('__details'),/questID: 2/);assert.match(h.get('__details'),/questName: Find Mum/);});
test('UI restores and saves validated window state',()=>{const h=setup();h.run('MAMChroniclesDB.settings.ui.point="TOPLEFT"; MAMChroniclesDB.settings.ui.x=40; MAMChroniclesDB.settings.ui.y=-30; MAMChroniclesDB.settings.ui.width=900; MAMChroniclesDB.settings.ui.height=650; local f=MAMChronicles.UI:Create(); __point,__relative,__relativePoint,__x,__y=f:GetPoint(); MAMChronicles.UI:SaveWindowState()');assert.equal(h.get('__point'),'TOPLEFT');assert.equal(h.get('__relativePoint'),'TOPLEFT');assert.equal(h.get('__x'),40);assert.equal(h.get('__y'),-30);assert.equal(h.get('MAMChroniclesDB.settings.ui.width'),900);assert.equal(h.get('MAMChroniclesDB.settings.ui.height'),650);});
test('UI toggles remembers active tab and registers for Escape',()=>{const h=setup();h.run('MAMChronicles.UI:Show(); MAMChronicles.UI:Toggle(); __hidden=not MAMChronicles.UI.frame:IsShown(); MAMChronicles.UI:Toggle(); __valid=MAMChronicles.UI:SetActiveTab("Statistics"); __invalid=MAMChronicles.UI:SetActiveTab("Secret")');assert.equal(h.get('__hidden'),true);assert.equal(h.get('MAMChronicles.UI.frame:IsShown()'),true);assert.equal(h.get('__valid'),true);assert.equal(h.get('__invalid'),false);assert.equal(h.get('MAMChroniclesDB.settings.ui.activeTab'),'Statistics');assert.equal(h.get('UISpecialFrames[1]'),'MAMChroniclesFrame');});
test('reset window restores centred defaults without moving the minimap launcher',()=>{const h=setup();h.run('local f=MAMChronicles.UI:Create(); MAMChroniclesDB.settings.ui.minimapAngle=12; f:SetSize(1000,700); f:ClearAllPoints(); f:SetPoint("TOPLEFT",UIParent,"TOPLEFT",50,-50); MAMChronicles.UI:SaveWindowState(); MAMChronicles.UI:ResetWindow(); __point=select(1,f:GetPoint())');assert.equal(h.get('__point'),'CENTER');assert.equal(h.get('MAMChroniclesDB.settings.ui.point'),'CENTER');assert.equal(h.get('MAMChroniclesDB.settings.ui.width'),780);assert.equal(h.get('MAMChroniclesDB.settings.ui.height'),560);assert.equal(h.get('MAMChroniclesDB.settings.ui.minimapAngle'),12);});
