import test from 'node:test'; import assert from 'node:assert/strict'; import { createHarness } from './harness.js';
const files=['Core.lua','Database.lua','EventStore.lua','Collectors.lua','Statistics.lua','Export.lua','Theme.lua','Toast.lua','Comms.lua','Dashboard.lua','UI.lua'];
function setup(){const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.EventStore:Append("character.death",{zone="Cave"},{occurredAt=1}); MAMChronicles.EventStore:Append("quest.completed",{questID=2,questName="Find Mum"},{occurredAt=2}); MAMChronicles.EventStore:Append("memory.manual",{text="Tea time"},{occurredAt=3})');return h;}
test('UI exposes six tabs and a fixed row pool',()=>{const h=setup();h.run('__a=MAMChronicles.UI:Create(); __same=(__a==MAMChronicles.UI:Create())');assert.equal(h.get('#MAMChronicles.UI.tabs'),6);assert.equal(h.get('MAMChronicles.UI.tabs[1]'),'Home');assert.equal(h.get('MAMChronicles.UI.tabs[2]'),'Chronicle');assert.equal(h.get('MAMChronicles.UI.tabs[3]'),'Medals');assert.equal(h.get('MAMChronicles.UI.tabs[6]'),'Diagnostics');assert.equal(h.get('#MAMChronicles.UI.rowPool'),30);assert.equal(h.get('__same'),true);});
test('UI provides an operational bottom-right resize handle',()=>{const h=setup();h.run('MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.resizeHandle ~= nil'),true);assert.equal(h.get('type(MAMChronicles.UI.resizeHandle.scripts.OnMouseDown)'), 'function');assert.equal(h.get('type(MAMChronicles.UI.resizeHandle.scripts.OnMouseUp)'), 'function');});
test('timeline model searches and filters newest first',()=>{const h=setup();h.run('__q=MAMChronicles.UI:BuildTimeline({filter="Quests",search="mum"}); __all=MAMChronicles.UI:BuildTimeline({filter="All"})');assert.equal(h.get('#__q'),1);assert.equal(h.get('__q[1].type'),'quest.completed');assert.equal(h.get('__all[1].type'),'memory.manual');});
test('slash commands dispatch memories exports diagnostics and help',()=>{const h=setup();h.slash('remember A lovely run');assert.equal(h.get('MAMChronicles.EventStore:Count("memory.manual")'),2);h.slash('export');assert.match(h.get('MAMChronicles.UI.copyText'),/^MAMCHRONICLES\/1/);h.slash('diag');assert.match(h.get('MAMChronicles.UI.copyText'),/Diagnostics/);h.slash('nonsense');assert.equal(h.get('MAMChronicles.UI.lastMessage'),'Commands: /mam, remember, stats, export, diag, help');});
test('copy views hide timeline controls that could intercept text selection',()=>{const h=setup();h.run('MAMChronicles.UI:Show(); MAMChronicles.UI:SetActiveTab("Chronicle"); __before=MAMChronicles.UI.rowButtons[1].shown; MAMChronicles.UI:ShowCopy("copy me"); __after=MAMChronicles.UI.rowButtons[1].shown; __copyShown=MAMChronicles.UI.copyBox.shown');assert.equal(h.get('__before'),true);assert.equal(h.get('__after'),false);assert.equal(h.get('__copyShown'),true);});
test('settings update validates supported values',()=>{const h=setup();h.run('__ok=MAMChronicles.UI:SetSetting("recordCoordinates",false); __bad=MAMChronicles.UI:SetSetting("secret",true)');assert.equal(h.get('__ok'),true);assert.equal(h.get('MAMChroniclesDB.settings.recordCoordinates'),false);assert.equal(h.get('__bad'),false);});
test('settings display the persisted Legendary-only loot threshold',()=>{const h=setup();h.run('MAMChroniclesDB.settings.notableQuality=5; MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.qualityButton and MAMChronicles.UI.qualityButton.text'),'Loot: Legendary only');});
test('timeline paging reaches entries beyond the fixed row pool',()=>{const h=setup();h.run('for i=1,35 do MAMChronicles.EventStore:Append("memory.manual",{text="Page "..i},{occurredAt=100+i}) end; MAMChronicles.UI.timelineOffset=30; __page=MAMChronicles.UI:GetVisibleTimeline()');assert.equal(h.get('#__page'),30);assert.equal(h.get('MAMChronicles.UI.timelineOffset'),8);assert.equal(h.get('__page[1].payload.text'),'Page 27');assert.equal(h.get('__page[30].type'),'character.death');});
test('current month range begins on calendar day one',()=>{const h=setup();h.run('__from,__to=MAMChronicles.UI:GetCurrentMonthRange()');assert.equal(h.get('os.date("%d",__from)'),'01');assert.equal(h.get('__to'),1790704800);});
test('event details expose useful allowlisted fields',()=>{const h=setup();h.run('__details=MAMChronicles.UI:FormatEventDetails(MAMChroniclesDB.events[2])');assert.match(h.get('__details'),/questID: 2/);assert.match(h.get('__details'),/questName: Find Mum/);});
test('UI restores and saves validated window state',()=>{const h=setup();h.run('MAMChroniclesDB.settings.ui.point="TOPLEFT"; MAMChroniclesDB.settings.ui.x=40; MAMChroniclesDB.settings.ui.y=-30; MAMChroniclesDB.settings.ui.width=900; MAMChroniclesDB.settings.ui.height=650; local f=MAMChronicles.UI:Create(); __point,__relative,__relativePoint,__x,__y=f:GetPoint(); MAMChronicles.UI:SaveWindowState()');assert.equal(h.get('__point'),'TOPLEFT');assert.equal(h.get('__relativePoint'),'TOPLEFT');assert.equal(h.get('__x'),40);assert.equal(h.get('__y'),-30);assert.equal(h.get('MAMChroniclesDB.settings.ui.width'),900);assert.equal(h.get('MAMChroniclesDB.settings.ui.height'),650);});
test('UI toggles remembers active tab and registers for Escape',()=>{const h=setup();h.run('MAMChronicles.UI:Show(); MAMChronicles.UI:Toggle(); __hidden=not MAMChronicles.UI.frame:IsShown(); MAMChronicles.UI:Toggle(); __valid=MAMChronicles.UI:SetActiveTab("Statistics"); __invalid=MAMChronicles.UI:SetActiveTab("Secret")');assert.equal(h.get('__hidden'),true);assert.equal(h.get('MAMChronicles.UI.frame:IsShown()'),true);assert.equal(h.get('__valid'),true);assert.equal(h.get('__invalid'),false);assert.equal(h.get('MAMChroniclesDB.settings.ui.activeTab'),'Statistics');assert.equal(h.get('UISpecialFrames[1]'),'MAMChroniclesFrame');});
test('reset window restores centred defaults without moving the minimap launcher',()=>{const h=setup();h.run('local f=MAMChronicles.UI:Create(); MAMChroniclesDB.settings.ui.minimapAngle=12; f:SetSize(1000,700); f:ClearAllPoints(); f:SetPoint("TOPLEFT",UIParent,"TOPLEFT",50,-50); MAMChronicles.UI:SaveWindowState(); MAMChronicles.UI:ResetWindow(); __point=select(1,f:GetPoint())');assert.equal(h.get('__point'),'CENTER');assert.equal(h.get('MAMChroniclesDB.settings.ui.point'),'CENTER');assert.equal(h.get('MAMChroniclesDB.settings.ui.width'),780);assert.equal(h.get('MAMChroniclesDB.settings.ui.height'),560);assert.equal(h.get('MAMChroniclesDB.settings.ui.minimapAngle'),12);});

const many='for i=1,40 do MAMChronicles.EventStore:Append("memory.manual",{text="Memory "..i},{occurredAt=100+i}) end';
test('active tab is highlighted and persisted',()=>{const h=setup();h.run('MAMChronicles.UI:Create(); MAMChronicles.UI:SetActiveTab("Statistics")');assert.equal(h.get('MAMChronicles.UI.tabButtons[4].highlighted'),true);assert.equal(h.get('MAMChronicles.UI.tabButtons[4].enabled'),false);assert.equal(h.get('MAMChronicles.UI.tabButtons[1].highlighted'),false);assert.equal(h.get('MAMChronicles.UI.tabButtons[1].enabled'),true);assert.equal(h.get('MAMChroniclesDB.settings.ui.activeTab'),'Statistics');});
test('filter menu selects an exact option without cycling',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI.filterButton.scripts.OnClick(UI.filterButton); UI.filterButton.scripts.OnClick(UI.filterButton); __still=UI.activeFilter; UI:OpenFilterMenu(UI.filterButton); for _,b in ipairs(UI.menuButtons) do if b.text=="Quests" then b.scripts.OnClick(b) end end; __bad=UI:SelectFilter("Bogus")');assert.equal(h.get('__still'),'All');assert.equal(h.get('MAMChronicles.UI.activeFilter'),'Quests');assert.equal(h.get('MAMChronicles.UI.filterButton.text'),'Filter: Quests');assert.equal(h.get('MAMChronicles.UI.menu.shown'),false);assert.equal(h.get('__bad'),false);assert.equal(h.get('MAMChronicles.UI.timelineOffset'),0);});
test('range menu selects an exact option without cycling',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); UI:OpenRangeMenu(UI.rangeButton); for _,b in ipairs(UI.menuButtons) do if b.text=="This Month" then b.scripts.OnClick(b) end end; __bad=UI:SelectRange("Bogus")');assert.equal(h.get('MAMChronicles.UI.activeRange'),'This Month');assert.equal(h.get('MAMChronicles.UI.rangeButton.text'),'Range: This Month');assert.equal(h.get('MAMChronicles.UI.menu.shown'),false);assert.equal(h.get('__bad'),false);});
test('timeline offset clamps and navigation disables at each boundary',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Create(); __n5=UI:SetTimelineOffset(-5,31); __big=UI:SetTimelineOffset(999,31); __bigNext=UI.nextButton.enabled; __bigPrev=UI.previousButton.enabled; __zero=UI:SetTimelineOffset(0,31); __zeroNext=UI.nextButton.enabled; __zeroPrev=UI.previousButton.enabled; __ten=UI:SetTimelineOffset(999,10); __tenBoth=UI.nextButton.enabled or UI.previousButton.enabled; __empty=UI:SetTimelineOffset(5,0)');assert.equal(h.get('__n5'),0);assert.equal(h.get('__big'),1);assert.equal(h.get('__bigNext'),false);assert.equal(h.get('__bigPrev'),true);assert.equal(h.get('__zero'),0);assert.equal(h.get('__zeroNext'),true);assert.equal(h.get('__zeroPrev'),false);assert.equal(h.get('__ten'),0);assert.equal(h.get('__tenBoth'),false);assert.equal(h.get('__empty'),0);});
test('scroll slider and mouse wheel share the same timeline offset',()=>{const h=setup();h.run(many+'; local UI=MAMChronicles.UI; UI:Show(); UI:SetActiveTab("Chronicle"); UI.slider:SetValue(7); __slider=UI.timelineOffset; UI.scrollFrame.scripts.OnMouseWheel(UI.scrollFrame,-1); __wheel=UI.timelineOffset; UI.scrollFrame.scripts.OnMouseWheel(UI.scrollFrame,-1); __clamped=UI.timelineOffset; __sliderValue=UI.slider.value');assert.equal(h.get('__slider'),7);assert.equal(h.get('__wheel'),12);assert.equal(h.get('__clamped'),13);assert.equal(h.get('__sliderValue'),13);});
test('polished UI retains exactly thirty reusable timeline rows',()=>{const h=setup();h.run(many+'; local UI=MAMChronicles.UI; UI:Show(); UI:SetTimelineOffset(5,43); UI:Refresh(); UI:SelectFilter("Quests")');assert.equal(h.get('#MAMChronicles.UI.rowPool'),30);assert.equal(h.get('#MAMChronicles.UI.rowButtons'),30);});
test('controls expose concise tooltip titles and instructions',()=>{const h=setup();h.run('local UI=MAMChronicles.UI; UI:Show(); __lines={}; for _,name in ipairs({"searchBox","filterButton","rangeButton","previousButton","nextButton","eraseButton"}) do local c=UI[name]; c.scripts.OnEnter(c); __lines[name]=#GameTooltip.lines; __shown=GameTooltip.shown; if name=="eraseButton" then __erase=GameTooltip.lines[2] end c.scripts.OnLeave(c); __hidden=GameTooltip.shown end');for(const name of ['searchBox','filterButton','rangeButton','previousButton','nextButton','eraseButton'])assert.equal(h.get(`__lines.${name}`)>=2,true,name);assert.equal(h.get('__hidden'),false);assert.match(h.get('__erase'),/Permanently/);});
test('empty and no-match states explain what to do',()=>{const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.UI:Show(); MAMChronicles.UI:SetActiveTab("Chronicle")');assert.match(h.get('MAMChronicles.UI.content.text'),/No Chronicle entries yet/);h.run('MAMChronicles.UI.search="zzz"; MAMChronicles.UI:Refresh()');assert.match(h.get('MAMChronicles.UI.content.text'),/match/);});
test('window minimum size uses SetResizeBounds when the client provides it',()=>{const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); local real=CreateFrame; CreateFrame=function(...) local f=real(...); function f:SetResizeBounds(a,b) self.resizeBounds={a,b} end; f.SetMinResize=nil; return f end; MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.frame.resizeBounds[1]'),620);assert.equal(h.get('MAMChronicles.UI.frame.resizeBounds[2]'),440);});
test('window minimum size falls back to SetMinResize on older clients',()=>{const h=createHarness();h.load(files);h.run('MAMChronicles:Boot(); MAMChronicles.UI:Create()');assert.equal(h.get('MAMChronicles.UI.frame.minResize[1]'),620);});
